@php
$hero=$page->sections[0]; $split=$page->sections[1]; $cards=$page->sections[2]; $rich=$page->sections[3]; $cta=$page->sections[4];
@endphp
<article data-public-page-projected="about">
<section data-about-region="about-hero" class="relative min-h-[620px] lg:min-h-[720px] flex items-end overflow-hidden">@if($hero->media)<img alt="{{ $hero->media->alt }}" @if($hero->media->decorative) aria-hidden="true" @endif class="absolute inset-0 w-full h-full object-cover object-top" src="{{ $hero->media->url }}"/>@endif<div class="absolute inset-0 bg-gradient-to-t from-wt-oxblood via-wt-oxblood/45 to-transparent"></div><div class="relative z-10 max-w-screen-xl mx-auto w-full px-6 lg:px-12 pb-16 lg:pb-24 pt-32"><p class="font-label text-xs tracking-[0.3em] uppercase text-wt-gold mb-4">{{ $hero->eyebrow }}</p><h1 class="font-heading text-5xl sm:text-6xl lg:text-7xl text-wt-cream max-w-3xl">{{ $hero->heading }}</h1><p class="font-body text-lg lg:text-xl text-wt-cream/85 font-light leading-relaxed max-w-2xl mt-6">{{ $hero->copy }}</p></div></section>
<section data-about-region="about-introduction" class="max-w-screen-xl mx-auto px-6 lg:px-12 py-16 lg:py-24"><div data-about-region="about-rich-text" class="max-w-3xl"><p class="font-label text-xs tracking-[0.25em] uppercase text-wt-gold mb-4">The Brand</p>{!! str_replace(['<h2>', '<p>'], ['<h2 class="font-heading text-4xl lg:text-5xl text-wt-oxblood leading-tight">', '<p class="font-body text-base lg:text-lg text-wt-charcoal/75 font-light leading-relaxed mt-6">'], $rich->html) !!}</div></section>
<section data-about-region="about-editorial" class="bg-wt-cream"><div class="max-w-screen-xl mx-auto grid grid-cols-1 lg:grid-cols-2">@if($split->media)<div class="aspect-[4/5] lg:aspect-auto min-h-[520px] overflow-hidden"><img alt="{{ $split->media->alt }}" @if($split->media->decorative) aria-hidden="true" @endif class="w-full h-full object-cover object-top" src="{{ $split->media->url }}"/></div>@endif<div class="px-6 sm:px-12 lg:px-16 py-16 lg:py-24 flex items-center"><div><p class="font-label text-xs tracking-[0.25em] uppercase text-wt-gold mb-4">A Considered Wardrobe</p><h2 class="font-heading text-4xl lg:text-5xl text-wt-oxblood">{{ $split->heading }}</h2><p class="font-body text-base text-wt-charcoal/75 font-light leading-relaxed mt-6">{{ $split->copy }}</p>@if($split->cta)<a class="inline-flex mt-8 font-label text-xs tracking-widest uppercase text-wt-oxblood border-b border-wt-gold pb-1" href="{{ $split->cta->url }}">{{ $split->cta->label }}</a>@endif</div></div></div></section>
<section data-about-region="about-principles" class="max-w-screen-xl mx-auto px-6 lg:px-12 py-16 lg:py-24"><div class="text-center max-w-2xl mx-auto mb-12"><p class="font-label text-xs tracking-[0.25em] uppercase text-wt-gold mb-4">Our Approach</p><h2 class="font-heading text-4xl lg:text-5xl text-wt-oxblood">{{ $cards->heading }}</h2></div><div class="grid grid-cols-1 md:grid-cols-3 gap-6">@foreach($cards->cards as $card)<div class="border border-wt-oxblood/15 p-8 lg:p-10"><p class="font-label text-[10px] tracking-[0.25em] uppercase text-wt-gold mb-4">{{ str_pad((string) $loop->iteration, 2, '0', STR_PAD_LEFT) }}</p><h3 class="font-heading text-2xl text-wt-oxblood">{{ $card->heading }}</h3><p class="font-body text-sm text-wt-charcoal/70 font-light leading-relaxed mt-4">{{ $card->copy }}</p></div>@endforeach</div></section>
<section data-about-region="about-cta" class="bg-wt-oxblood relative overflow-hidden"><div aria-hidden="true" class="absolute inset-0 wt-footer-pattern" style='background-image: url("/website/images/eab6bab5d_bg.jpg");'></div><div class="relative max-w-3xl mx-auto px-6 py-20 lg:py-28 text-center"><p class="font-label text-xs tracking-[0.25em] uppercase text-wt-gold mb-4">The William Taylor Wardrobe</p><h2 class="font-heading text-4xl lg:text-5xl text-wt-cream">{{ $cta->heading }}</h2><p class="font-body text-base text-wt-cream/70 font-light leading-relaxed mt-5">{{ $cta->copy }}</p><a class="btn-gold inline-flex mt-8 px-10 py-4 text-xs tracking-widest uppercase" href="{{ $cta->primaryCta->url }}">{{ $cta->primaryCta->label }}</a></div></section>
</article>