import { chromium } from '@playwright/test';
import { execFileSync, spawn } from 'node:child_process';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { join, resolve } from 'node:path';
import pixelmatch from 'pixelmatch';
import { PNG } from 'pngjs';
const root=resolve('.'), out=join(root,'storage','app','evidence','be-4h-b','browser'), db=join(root,'storage','app','evidence','be-4h-0-cloudinary.sqlite');
await mkdir(join(out,'diff'),{recursive:true});
const states=[['site-off-page-off',8111,false,false],['site-on-page-off',8112,false,true],['site-off-page-on',8113,true,false],['site-on-page-on',8114,true,true]].map(([name,port,page,site])=>({name,port,page,site}));
const sizes=[['desktop',1440,900],['tablet',768,1024],['mobile',375,812]].map(([name,width,height])=>({name,width,height}));
const findings=[];
const leakPattern=/(data-(?:public-)?revision(?:-id)?|currentPublicRevision|current_public_revision|publication[_-]state|candidate[_-]revision|revision[_-]checksum|workflow[_-]transition|\\b[0-9A-HJKMNP-TV-Z]{26}\\b)/gi;
const stop=c=>{try{execFileSync('taskkill',['/pid',String(c.pid),'/T','/F'],{stdio:'ignore',windowsHide:true})}catch{}};
const ready=async page=>{await page.evaluate(async()=>{await document.fonts?.ready;await Promise.race([Promise.all([...document.images].filter(i=>!i.complete).map(i=>new Promise(r=>{i.addEventListener('load',r,{once:true});i.addEventListener('error',r,{once:true})}))),new Promise(r=>setTimeout(r,10000))]);window.scrollTo(0,0)});await page.addStyleTag({content:'*,*::before,*::after{animation-duration:0s!important;transition-duration:0s!important;scroll-behavior:auto!important}'});await page.waitForTimeout(50)};
const facts=()=>{const rect=e=>{const r=e.getBoundingClientRect();return {x:r.x,y:r.y+scrollY,width:r.width,height:r.height,right:r.right,bottom:r.bottom+scrollY}};const regions={};document.querySelectorAll('[data-about-region]').forEach(e=>regions[e.dataset.aboutRegion]=rect(e));const images=[...document.querySelectorAll('main img')].map(e=>({alt:e.alt,rect:rect(e),aspect:e.naturalWidth&&e.naturalHeight?e.naturalWidth/e.naturalHeight:null,fit:getComputedStyle(e).objectFit}));return {projected:!!document.querySelector('[data-public-page-projected="about"]'),h1:document.querySelectorAll('h1').length,headings:[...document.querySelectorAll('main h1,main h2,main h3')].map(e=>({level:e.tagName,text:e.textContent.trim()})),sections:[...document.querySelectorAll('main section[data-about-region]')].map(e=>e.dataset.aboutRegion),cards:document.querySelectorAll('[data-about-region="about-principles"] .grid>div').length,columns:getComputedStyle(document.querySelector('[data-about-region="about-principles"] .grid')).gridTemplateColumns.split(' ').length,overflow:document.documentElement.scrollWidth>document.documentElement.clientWidth,page:{width:document.documentElement.scrollWidth,height:document.documentElement.scrollHeight},regions,images};};
for(const state of states){const child=spawn('php',['artisan','serve','--host=127.0.0.1',`--port=${state.port}`],{cwd:root,windowsHide:true,env:{...process.env,DB_CONNECTION:'sqlite',DB_DATABASE:db,MEDIA_PROVIDER:'cloudinary',PUBLIC_PAGE_PROJECTION:String(state.page),PUBLIC_SITE_CONTENT_PROJECTION:String(state.site)},stdio:'ignore'});try{for(let i=0;i<80;i++){try{if((await fetch(`http://127.0.0.1:${state.port}/about`)).ok)break}catch{}await new Promise(r=>setTimeout(r,250))}const browser=await chromium.launch({headless:true});for(const size of sizes){const context=await browser.newContext({viewport:{width:size.width,height:size.height},deviceScaleFactor:1,colorScheme:'light',locale:'en-US',reducedMotion:'reduce'});await context.clearCookies();const page=await context.newPage();await page.route('https://res.cloudinary.com/**',async route=>{const u=route.request().url();const local=u.includes('storefront-306170464-')?'public/website/images/306170464_Screenshot2026-07-10at215946.png':u.includes('storefront-da608a583-')?'public/website/images/da608a583_image.jpg':null;if(local){await route.fulfill({path:join(root,local),contentType:local.endsWith('.png')?'image/png':'image/jpeg'});}else await route.continue();});const consoleMessages=[],failedRequests=[];page.on('console',m=>{if(['error','warning'].includes(m.type()))consoleMessages.push(`${m.type()}: ${m.text()}`)});page.on('requestfailed',r=>failedRequests.push(`${r.method()} ${r.url()} ${r.failure()?.errorText}`));const response=await page.goto(`http://127.0.0.1:${state.port}/about`,{waitUntil:'domcontentloaded',timeout:60000});await ready(page);const data=await page.evaluate(facts);const responseHtml=await response.text();const liveDom=await page.content();const responseHeaders=await response.allHeaders();const responseLeaks=[...new Set(responseHtml.match(leakPattern)??[])];const domLeaks=[...new Set(liveDom.match(leakPattern)??[])];const headerLeaks=[...new Set(JSON.stringify(responseHeaders).match(leakPattern)??[])];if(state.page){await writeFile(join(out,`${state.name}-${size.name}-response.html`),responseHtml);await writeFile(join(out,`${state.name}-${size.name}-dom.html`),liveDom);}const path=join(out,`${state.name}-${size.name}.png`);await page.screenshot({path,fullPage:true,animations:'disabled'});findings.push({state:state.name,viewport:`${size.width}x${size.height}`,pageProjection:state.page,siteProjection:state.site,status:response?.status(),...data,responseLeaks,domLeaks,headerLeaks,consoleMessages,failedRequests,path:path.slice(root.length+1).replaceAll('\\','/')});await context.close()}await browser.close()}finally{stop(child)}}
const comparisons=[];
for(const size of sizes){const a=findings.find(x=>x.state==='site-off-page-off'&&x.viewport===`${size.width}x${size.height}`),b=findings.find(x=>x.state==='site-off-page-on'&&x.viewport===a.viewport);const deltas={};for(const k of Object.keys(a.regions)){const ar=a.regions[k],br=b.regions[k];deltas[k]=Object.fromEntries(['x','y','width','height'].map(p=>[p,Math.abs(ar[p]-br[p])]))}const pa=PNG.sync.read(await readFile(join(root,a.path))),pb=PNG.sync.read(await readFile(join(root,b.path)));let screenshot={status:'dimension-mismatch',static:[pa.width,pa.height],projected:[pb.width,pb.height]};if(pa.width===pb.width&&pa.height===pb.height){const diff=new PNG({width:pa.width,height:pa.height});const pixels=pixelmatch(pa.data,pb.data,diff.data,pa.width,pa.height,{threshold:.1,includeAA:true});const dp=join(out,'diff',`${size.name}.png`);await writeFile(dp,PNG.sync.write(diff));screenshot={status:pixels?'different':'identical',pixels,total:pa.width*pa.height,percent:pixels/(pa.width*pa.height)*100,diffPath:dp.slice(root.length+1).replaceAll('\\','/')}}comparisons.push({viewport:a.viewport,geometryTolerancePx:2,maxGeometryDeltaPx:Math.max(...Object.values(deltas).flatMap(x=>Object.values(x))),heightDeltaPx:Math.abs(a.page.height-b.page.height),regions:deltas,semantics:{h1:a.h1===b.h1,headings:JSON.stringify(a.headings)===JSON.stringify(b.headings),sectionOrder:JSON.stringify(a.sections)===JSON.stringify(b.sections),cards:a.cards===b.cards,columns:a.columns===b.columns,overflow:a.overflow===b.overflow},screenshot})}
const metadata={generatedAt:new Date().toISOString(),chromium:await chromium.launch({headless:true}).then(async b=>{const v=b.version();await b.close();return v}),route:'/about',database:'storage/app/evidence/be-4h-0-cloudinary.sqlite',provider:'cloudinary',deviceScaleFactor:1,rule:'Stable region x, y, width and height deltas must be at most 2 CSS pixels. Screenshot pixel differences are reported, not used as a geometry waiver.'};
await writeFile(join(out,'findings.json'),JSON.stringify({metadata,findings,comparisons},null,2));await writeFile(join(out,'comparison.json'),JSON.stringify(comparisons,null,2));console.log(JSON.stringify({captures:findings.length,failures:findings.filter(x=>x.status!==200||x.h1!==1||x.overflow||x.consoleMessages.length||x.failedRequests.length||x.responseLeaks.length||x.domLeaks.length||x.headerLeaks.length).length,comparisons:comparisons.map(x=>({viewport:x.viewport,maxGeometryDeltaPx:x.maxGeometryDeltaPx,heightDeltaPx:x.heightDeltaPx,differencePercent:x.screenshot.percent??null}))},null,2));