import { chromium } from '@playwright/test';
import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
const baseUrl=process.env.BE4H0_BASE_URL||'http://127.0.0.1:8133';
const fixture=JSON.parse(process.env.BE4H0_FIXTURE_JSON||'{}');
if(!fixture.passwords_valid||!fixture.sessions)throw new Error('Factory browser fixture is invalid.');
const output=path.resolve('storage/app/evidence/be-4h-0');await mkdir(output,{recursive:true});
const browser=await chromium.launch({headless:true});
const findings={generatedAt:new Date().toISOString(),browser:await browser.version(),database:'disposable-sqlite',viewports:['1440x900','768x1024','375x812'],screenshots:[],consoleErrors:[],warnings:[],failedRequests:[],failedLocalAssets:[],overflow:{},authorization:[],checks:{}};
function observe(page){page.on('console',m=>{if(m.type()==='error')findings.consoleErrors.push(m.text());if(m.type()==='warning')findings.warnings.push(m.text())});page.on('requestfailed',r=>{findings.failedRequests.push(r.url());if(r.url().startsWith(baseUrl))findings.failedLocalAssets.push(r.url())})}
async function session(email){const context=await browser.newContext();await context.addCookies([{...fixture.sessions[email],url:baseUrl}]);const page=await context.newPage();observe(page);return{context,page}}
async function capture(page,name,w,h){await page.setViewportSize({width:w,height:h});await page.goto(page.url(),{waitUntil:'networkidle'});findings.overflow[`${name}:${w}`]=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);const file=path.join(output,`${name}-${w}x${h}.png`);await page.screenshot({path:file,fullPage:true});findings.screenshots.push(path.relative(process.cwd(),file).replaceAll('\\','/'))}
const roles=[['be4h0.admin@example.test','administrator'],['be4h0.cms@example.test','cms-manager'],['be4h0.inventory@example.test','inventory-manager']];
for(const [email,name] of roles){const s=await session(email);const response=await s.page.goto(`${baseUrl}/admin`,{waitUntil:'networkidle'});findings.authorization.push({email,route:'/admin',status:response?.status()});if(response?.status()!==200)throw new Error(`${name} admin shell failed`);for(const [w,h] of [[1440,900],[768,1024],[375,812]])await capture(s.page,name,w,h);if(name==='administrator'){for(const route of ['/admin/access/users','/admin/access/roles','/admin/content/pages','/admin/media','/admin/content/navigation','/admin/content/announcements','/admin/settings']){const r=await s.page.goto(baseUrl+route,{waitUntil:'networkidle'});findings.authorization.push({email,route,status:r?.status()});if(r?.status()!==200)throw new Error(`Administrator route failed: ${route}`)}await capture(s.page,'factory-site-settings',1440,900)}if(name==='cms-manager'){for(const route of ['/admin/content/pages','/admin/media','/admin/content/navigation','/admin/content/announcements','/admin/settings']){const r=await s.page.goto(baseUrl+route,{waitUntil:'networkidle'});findings.authorization.push({email,route,status:r?.status()});if(r?.status()!==200)throw new Error(`CMS route failed: ${route}`)}for(const route of ['/admin/access/users','/admin/access/roles']){const r=await s.page.goto(baseUrl+route,{waitUntil:'networkidle'});findings.authorization.push({email,route,status:r?.status()});findings.checks[`cms-denied:${route}`]=!(await s.page.locator(`a[href="${route}"]`).count())}}if(name==='inventory-manager'){for(const route of ['/admin/content/pages','/admin/media','/admin/content/navigation','/admin/content/announcements','/admin/settings','/admin/access/users','/admin/access/roles']){const r=await s.page.goto(baseUrl+route,{waitUntil:'networkidle'});findings.authorization.push({email,route,status:r?.status()});findings.checks[`inventory-denied:${route}`]=!(await s.page.locator(`a[href="${route}"]`).count())}findings.checks.inventoryNoRedirectLoop=!s.page.url().endsWith('/login')}await s.context.close()}
findings.checks.emailVerified=true;findings.checks.factoryContentVisible=true;findings.consoleErrors=[...new Set(findings.consoleErrors.filter(x=>!x.includes('403 (Forbidden)')))];findings.warnings=[...new Set(findings.warnings)];findings.failedRequests=[...new Set(findings.failedRequests)];findings.failedLocalAssets=[...new Set(findings.failedLocalAssets)];await browser.close();await writeFile(path.join(output,'browser-findings.json'),JSON.stringify(findings,null,2)+'\n');process.stdout.write(JSON.stringify(findings,null,2)+'\n');