<?php

return [
    'schema_version' => 1,
    'factory_version' => 'william-taylor-factory-v1',
    'entries' => json_decode(<<<'JSON'
[
    {
        "logical_key":  "storefront-0368482bc-image",
        "source_kind":  "local",
        "source":  "public/website/images/0368482bc_image.jpg",
        "sha256":  "974a519ae54c5825aa630b76e44a3b7db3355bb1257d3808714ba9c7388caf20",
        "resource_type":  "image",
        "mime_type":  "image/jpeg",
        "title":  "0368482bc_image",
        "alt_text":  "William Taylor storefront image",
        "decorative":  false,
        "rights":  "Client supplied and licensed for production",
        "usage":  "Current approved storefront imagery",
        "future_domain":  "reserved",
        "provider_suffix":  "images/storefront-0368482bc-image",
        "required":  true,
        "factory_version":  "william-taylor-factory-v1"
    },
    {
        "logical_key":  "storefront-0f5271d44-generated-image",
        "source_kind":  "local",
        "source":  "public/website/images/0f5271d44_generated_image.png",
        "sha256":  "229d93531512c13de4bf2da654f2724e110963e1e24bb45842284fa5c0353c82",
        "resource_type":  "image",
        "mime_type":  "image/png",
        "title":  "0f5271d44_generated_image",
        "alt_text":  "William Taylor storefront image",
        "decorative":  false,
        "rights":  "Client supplied and licensed for production",
        "usage":  "Current approved storefront imagery",
        "future_domain":  "reserved",
        "provider_suffix":  "images/storefront-0f5271d44-generated-image",
        "required":  true,
        "factory_version":  "william-taylor-factory-v1"
    },
    {
        "logical_key":  "storefront-1aaa8bb8c-generated-image",
        "source_kind":  "local",
        "source":  "public/website/images/1aaa8bb8c_generated_image.png",
        "sha256":  "33d67925f66c04ce44069ddd3f1fa6eefa078662c9c191433e0209a420fd0370",
        "resource_type":  "image",
        "mime_type":  "image/png",
        "title":  "1aaa8bb8c_generated_image",
        "alt_text":  "William Taylor storefront image",
        "decorative":  false,
        "rights":  "Client supplied and licensed for production",
        "usage":  "Current approved storefront imagery",
        "future_domain":  "reserved",
        "provider_suffix":  "images/storefront-1aaa8bb8c-generated-image",
        "required":  true,
        "factory_version":  "william-taylor-factory-v1"
    },
    {
        "logical_key":  "storefront-1c4c991a1-ethumb",
        "source_kind":  "local",
        "source":  "public/website/images/1c4c991a1_ethumb.jpg",
        "sha256":  "7536883f297cc9fc045c5822b427fcca15fc2a465b0d952be4a9cbb350af2485",
        "resource_type":  "image",
        "mime_type":  "image/jpeg",
        "title":  "1c4c991a1_ethumb",
        "alt_text":  "William Taylor storefront image",
        "decorative":  false,
        "rights":  "Client supplied and licensed for production",
        "usage":  "Current approved storefront imagery",
        "future_domain":  "reserved",
        "provider_suffix":  "images/storefront-1c4c991a1-ethumb",
        "required":  true,
        "factory_version":  "william-taylor-factory-v1"
    },
    {
        "logical_key":  "storefront-21856d944-generated-image",
        "source_kind":  "local",
        "source":  "public/website/images/21856d944_generated_image.png",
        "sha256":  "5a3124a54f16446cde6959c2aa493c60c5cf00e1393256b57f066016e82228b7",
        "resource_type":  "image",
        "mime_type":  "image/png",
        "title":  "21856d944_generated_image",
        "alt_text":  "William Taylor storefront image",
        "decorative":  false,
        "rights":  "Client supplied and licensed for production",
        "usage":  "Current approved storefront imagery",
        "future_domain":  "reserved",
        "provider_suffix":  "images/storefront-21856d944-generated-image",
        "required":  true,
        "factory_version":  "william-taylor-factory-v1"
    },
    {
        "logical_key":  "storefront-2946546dd-image",
        "source_kind":  "local",
        "source":  "public/website/images/2946546dd_image.jpeg",
        "sha256":  "f698606d4e07bd3a96cd11474fcdb85b715dafdf74b52127414201f5dafc798c",
        "resource_type":  "image",
        "mime_type":  "image/jpeg",
        "title":  "2946546dd_image",
        "alt_text":  "William Taylor storefront image",
        "decorative":  false,
        "rights":  "Client supplied and licensed for production",
        "usage":  "Current approved storefront imagery",
        "future_domain":  "reserved",
        "provider_suffix":  "images/storefront-2946546dd-image",
        "required":  true,
        "factory_version":  "william-taylor-factory-v1"
    },
    {
        "logical_key":  "storefront-306170464-screenshot2026-07-10at215946",
        "source_kind":  "local",
        "source":  "public/website/images/306170464_Screenshot2026-07-10at215946.png",
        "sha256":  "381be4dc9ae047f8e2bfe5fd723341dabd54cf784fb3241d792957e542e758ea",
        "resource_type":  "image",
        "mime_type":  "image/png",
        "title":  "306170464_Screenshot2026-07-10at215946",
        "alt_text":  "William Taylor storefront image",
        "decorative":  false,
        "rights":  "Client supplied and licensed for production",
        "usage":  "Current approved storefront imagery",
        "future_domain":  "reserved",
        "provider_suffix":  "images/storefront-306170464-screenshot2026-07-10at215946",
        "required":  true,
        "factory_version":  "william-taylor-factory-v1"
    },
    {
        "logical_key":  "storefront-5e4275a15-generated-image",
        "source_kind":  "local",
        "source":  "public/website/images/5e4275a15_generated_image.png",
        "sha256":  "6172e94cf5012e7d6220a62a66db393f92e63edff587dce867476fd1fdfddcf7",
        "resource_type":  "image",
        "mime_type":  "image/png",
        "title":  "5e4275a15_generated_image",
        "alt_text":  "William Taylor storefront image",
        "decorative":  false,
        "rights":  "Client supplied and licensed for production",
        "usage":  "Current approved storefront imagery",
        "future_domain":  "reserved",
        "provider_suffix":  "images/storefront-5e4275a15-generated-image",
        "required":  true,
        "factory_version":  "william-taylor-factory-v1"
    },
    {
        "logical_key":  "storefront-601f1442e-image",
        "source_kind":  "local",
        "source":  "public/website/images/601f1442e_image.jpg",
        "sha256":  "9ffeb878ff13826b7f93f6b70760461efce87ba946324d066b817d523713545a",
        "resource_type":  "image",
        "mime_type":  "image/jpeg",
        "title":  "601f1442e_image",
        "alt_text":  "William Taylor storefront image",
        "decorative":  false,
        "rights":  "Client supplied and licensed for production",
        "usage":  "Current approved storefront imagery",
        "future_domain":  "reserved",
        "provider_suffix":  "images/storefront-601f1442e-image",
        "required":  true,
        "factory_version":  "william-taylor-factory-v1"
    },
    {
        "logical_key":  "storefront-62414b4d4-generated-image",
        "source_kind":  "local",
        "source":  "public/website/images/62414b4d4_generated_image.png",
        "sha256":  "4bf6f1d9a6456c121157f5ab1810b1b2a0f709637bd39de99f323a96b8e93d67",
        "resource_type":  "image",
        "mime_type":  "image/png",
        "title":  "62414b4d4_generated_image",
        "alt_text":  "William Taylor storefront image",
        "decorative":  false,
        "rights":  "Client supplied and licensed for production",
        "usage":  "Current approved storefront imagery",
        "future_domain":  "reserved",
        "provider_suffix":  "images/storefront-62414b4d4-generated-image",
        "required":  true,
        "factory_version":  "william-taylor-factory-v1"
    },
    {
        "logical_key":  "storefront-6d46d522f-image",
        "source_kind":  "local",
        "source":  "public/website/images/6d46d522f_image.jpg",
        "sha256":  "e7e76b2ab041b72fb628866b84ab2975e6c1f34af746c7fa8b6b932e9c585dad",
        "resource_type":  "image",
        "mime_type":  "image/jpeg",
        "title":  "6d46d522f_image",
        "alt_text":  "William Taylor storefront image",
        "decorative":  false,
        "rights":  "Client supplied and licensed for production",
        "usage":  "Current approved storefront imagery",
        "future_domain":  "reserved",
        "provider_suffix":  "images/storefront-6d46d522f-image",
        "required":  true,
        "factory_version":  "william-taylor-factory-v1"
    },
    {
        "logical_key":  "storefront-6e114010e-image",
        "source_kind":  "local",
        "source":  "public/website/images/6e114010e_image.jpg",
        "sha256":  "19e0b9fb131d05e700d993afc7143760c89258ad38f4464a516a1cefe5784f79",
        "resource_type":  "image",
        "mime_type":  "image/jpeg",
        "title":  "6e114010e_image",
        "alt_text":  "William Taylor storefront image",
        "decorative":  false,
        "rights":  "Client supplied and licensed for production",
        "usage":  "Current approved storefront imagery",
        "future_domain":  "reserved",
        "provider_suffix":  "images/storefront-6e114010e-image",
        "required":  true,
        "factory_version":  "william-taylor-factory-v1"
    },
    {
        "logical_key":  "storefront-7a24ade71-logo-3",
        "source_kind":  "local",
        "source":  "public/website/images/7a24ade71_LOGO-3.png",
        "sha256":  "9fe7b63c8abd0826491e85f0930a17aeacc9db4d86c6579b0d99fac3dd9a1d57",
        "resource_type":  "image",
        "mime_type":  "image/png",
        "title":  "7a24ade71_LOGO-3",
        "alt_text":  "William Taylor storefront image",
        "decorative":  false,
        "rights":  "Client supplied and licensed for production",
        "usage":  "Current approved storefront imagery",
        "future_domain":  "reserved",
        "provider_suffix":  "images/storefront-7a24ade71-logo-3",
        "required":  true,
        "factory_version":  "william-taylor-factory-v1"
    },
    {
        "logical_key":  "storefront-7e8ceffc2-generated-image",
        "source_kind":  "local",
        "source":  "public/website/images/7e8ceffc2_generated_image.png",
        "sha256":  "4b4f90f9218fe7757c7bff0bb55a9337fb342ae96549eb3af2638c26c31962c1",
        "resource_type":  "image",
        "mime_type":  "image/png",
        "title":  "7e8ceffc2_generated_image",
        "alt_text":  "William Taylor storefront image",
        "decorative":  false,
        "rights":  "Client supplied and licensed for production",
        "usage":  "Current approved storefront imagery",
        "future_domain":  "reserved",
        "provider_suffix":  "images/storefront-7e8ceffc2-generated-image",
        "required":  true,
        "factory_version":  "william-taylor-factory-v1"
    },
    {
        "logical_key":  "storefront-81f56a965-image",
        "source_kind":  "local",
        "source":  "public/website/images/81f56a965_image.jpg",
        "sha256":  "cf1716d2b3cacc5119910279f0d8112a613653fbe6b508f213ce51c6f59ca45f",
        "resource_type":  "image",
        "mime_type":  "image/jpeg",
        "title":  "81f56a965_image",
        "alt_text":  "William Taylor storefront image",
        "decorative":  false,
        "rights":  "Client supplied and licensed for production",
        "usage":  "Current approved storefront imagery",
        "future_domain":  "reserved",
        "provider_suffix":  "images/storefront-81f56a965-image",
        "required":  true,
        "factory_version":  "william-taylor-factory-v1"
    },
    {
        "logical_key":  "storefront-84c5dcdc1-image",
        "source_kind":  "local",
        "source":  "public/website/images/84c5dcdc1_image.jpg",
        "sha256":  "e8b0792041eff8d106b6f8fb4160184e5da781337e4a259c2adf0e500450bc9b",
        "resource_type":  "image",
        "mime_type":  "image/jpeg",
        "title":  "84c5dcdc1_image",
        "alt_text":  "William Taylor storefront image",
        "decorative":  false,
        "rights":  "Client supplied and licensed for production",
        "usage":  "Current approved storefront imagery",
        "future_domain":  "reserved",
        "provider_suffix":  "images/storefront-84c5dcdc1-image",
        "required":  true,
        "factory_version":  "william-taylor-factory-v1"
    },
    {
        "logical_key":  "storefront-8572d276e-thumb",
        "source_kind":  "local",
        "source":  "public/website/images/8572d276e_thumb.jpg",
        "sha256":  "c1d53226e9fe1deb51b82316d5efe0be2335fad6dd031d2dbd7b9e09f4bbf212",
        "resource_type":  "image",
        "mime_type":  "image/jpeg",
        "title":  "8572d276e_thumb",
        "alt_text":  "William Taylor storefront image",
        "decorative":  false,
        "rights":  "Client supplied and licensed for production",
        "usage":  "Current approved storefront imagery",
        "future_domain":  "reserved",
        "provider_suffix":  "images/storefront-8572d276e-thumb",
        "required":  true,
        "factory_version":  "william-taylor-factory-v1"
    },
    {
        "logical_key":  "storefront-86df796c0-thumb",
        "source_kind":  "local",
        "source":  "public/website/images/86df796c0_thumb.jpg",
        "sha256":  "a3bac5d6750a5faa10f1969c27c90b2ee04b78c8a0f80ca51e00270ead8fe058",
        "resource_type":  "image",
        "mime_type":  "image/jpeg",
        "title":  "86df796c0_thumb",
        "alt_text":  "William Taylor storefront image",
        "decorative":  false,
        "rights":  "Client supplied and licensed for production",
        "usage":  "Current approved storefront imagery",
        "future_domain":  "reserved",
        "provider_suffix":  "images/storefront-86df796c0-thumb",
        "required":  true,
        "factory_version":  "william-taylor-factory-v1"
    },
    {
        "logical_key":  "storefront-8a8dd5e57-image",
        "source_kind":  "local",
        "source":  "public/website/images/8a8dd5e57_image.jpg",
        "sha256":  "108095c5c8bf95c9f4525d6ad901131aa4385a7a559326f879ecd1ac3b05e566",
        "resource_type":  "image",
        "mime_type":  "image/jpeg",
        "title":  "8a8dd5e57_image",
        "alt_text":  "William Taylor storefront image",
        "decorative":  false,
        "rights":  "Client supplied and licensed for production",
        "usage":  "Current approved storefront imagery",
        "future_domain":  "reserved",
        "provider_suffix":  "images/storefront-8a8dd5e57-image",
        "required":  true,
        "factory_version":  "william-taylor-factory-v1"
    },
    {
        "logical_key":  "storefront-8d7122778-image",
        "source_kind":  "local",
        "source":  "public/website/images/8d7122778_image.jpg",
        "sha256":  "b3f05b98404b95dece28511b4386a8520eb061c90294d8000e506ec9c8efce54",
        "resource_type":  "image",
        "mime_type":  "image/jpeg",
        "title":  "8d7122778_image",
        "alt_text":  "William Taylor storefront image",
        "decorative":  false,
        "rights":  "Client supplied and licensed for production",
        "usage":  "Current approved storefront imagery",
        "future_domain":  "reserved",
        "provider_suffix":  "images/storefront-8d7122778-image",
        "required":  true,
        "factory_version":  "william-taylor-factory-v1"
    },
    {
        "logical_key":  "storefront-8d99836ea-logo-3",
        "source_kind":  "local",
        "source":  "public/website/images/8d99836ea_LOGO-3.png",
        "sha256":  "9fe7b63c8abd0826491e85f0930a17aeacc9db4d86c6579b0d99fac3dd9a1d57",
        "resource_type":  "image",
        "mime_type":  "image/png",
        "title":  "8d99836ea_LOGO-3",
        "alt_text":  "William Taylor storefront image",
        "decorative":  false,
        "rights":  "Client supplied and licensed for production",
        "usage":  "Current approved storefront imagery",
        "future_domain":  "reserved",
        "provider_suffix":  "images/storefront-8d99836ea-logo-3",
        "required":  true,
        "factory_version":  "william-taylor-factory-v1"
    },
    {
        "logical_key":  "storefront-93216c40a-image",
        "source_kind":  "local",
        "source":  "public/website/images/93216c40a_image.jpg",
        "sha256":  "7f82ee7946017825568c23110c846dbeea4553b873bec486c802eabcb6ceff97",
        "resource_type":  "image",
        "mime_type":  "image/jpeg",
        "title":  "93216c40a_image",
        "alt_text":  "William Taylor storefront image",
        "decorative":  false,
        "rights":  "Client supplied and licensed for production",
        "usage":  "Current approved storefront imagery",
        "future_domain":  "reserved",
        "provider_suffix":  "images/storefront-93216c40a-image",
        "required":  true,
        "factory_version":  "william-taylor-factory-v1"
    },
    {
        "logical_key":  "storefront-98e3f82c0-image",
        "source_kind":  "local",
        "source":  "public/website/images/98e3f82c0_image.jpg",
        "sha256":  "4c200c8217b555a714b4456fa804385a1a62a8b70d3187d749c06dc8a4602cb9",
        "resource_type":  "image",
        "mime_type":  "image/jpeg",
        "title":  "98e3f82c0_image",
        "alt_text":  "William Taylor storefront image",
        "decorative":  false,
        "rights":  "Client supplied and licensed for production",
        "usage":  "Current approved storefront imagery",
        "future_domain":  "reserved",
        "provider_suffix":  "images/storefront-98e3f82c0-image",
        "required":  true,
        "factory_version":  "william-taylor-factory-v1"
    },
    {
        "logical_key":  "storefront-9c30daca8-image",
        "source_kind":  "local",
        "source":  "public/website/images/9c30daca8_image.jpg",
        "sha256":  "cc48070b644c63bb514a1c193464388a58fcb6b42314619b46ea867de9104a70",
        "resource_type":  "image",
        "mime_type":  "image/jpeg",
        "title":  "9c30daca8_image",
        "alt_text":  "William Taylor storefront image",
        "decorative":  false,
        "rights":  "Client supplied and licensed for production",
        "usage":  "Current approved storefront imagery",
        "future_domain":  "reserved",
        "provider_suffix":  "images/storefront-9c30daca8-image",
        "required":  true,
        "factory_version":  "william-taylor-factory-v1"
    },
    {
        "logical_key":  "storefront-9c691e236-image",
        "source_kind":  "local",
        "source":  "public/website/images/9c691e236_image.jpg",
        "sha256":  "d10d6922bc755f8f7e3eeac0f8b284a986ef33e3b7c3061d2ee50bd5ae221f29",
        "resource_type":  "image",
        "mime_type":  "image/jpeg",
        "title":  "9c691e236_image",
        "alt_text":  "William Taylor storefront image",
        "decorative":  false,
        "rights":  "Client supplied and licensed for production",
        "usage":  "Current approved storefront imagery",
        "future_domain":  "reserved",
        "provider_suffix":  "images/storefront-9c691e236-image",
        "required":  true,
        "factory_version":  "william-taylor-factory-v1"
    },
    {
        "logical_key":  "storefront-9cf5386c6-image",
        "source_kind":  "local",
        "source":  "public/website/images/9cf5386c6_image.jpg",
        "sha256":  "21048e3ddb2cf9493a1c74fa08f1717d1344436db4e714ccc3d04b3537322996",
        "resource_type":  "image",
        "mime_type":  "image/jpeg",
        "title":  "9cf5386c6_image",
        "alt_text":  "William Taylor storefront image",
        "decorative":  false,
        "rights":  "Client supplied and licensed for production",
        "usage":  "Current approved storefront imagery",
        "future_domain":  "reserved",
        "provider_suffix":  "images/storefront-9cf5386c6-image",
        "required":  true,
        "factory_version":  "william-taylor-factory-v1"
    },
    {
        "logical_key":  "storefront-a3ab973a9-waa2",
        "source_kind":  "local",
        "source":  "public/website/images/a3ab973a9_waa2.png",
        "sha256":  "fa80666786cc93aaa7de0ada94c775278da6fb3964b8c2ac491e20fa61c2a25c",
        "resource_type":  "image",
        "mime_type":  "image/png",
        "title":  "a3ab973a9_waa2",
        "alt_text":  "William Taylor storefront image",
        "decorative":  false,
        "rights":  "Client supplied and licensed for production",
        "usage":  "Current approved storefront imagery",
        "future_domain":  "reserved",
        "provider_suffix":  "images/storefront-a3ab973a9-waa2",
        "required":  true,
        "factory_version":  "william-taylor-factory-v1"
    },
    {
        "logical_key":  "storefront-a5552b423-3",
        "source_kind":  "local",
        "source":  "public/website/images/a5552b423_3.jpg",
        "sha256":  "576b636c8dd0f551461b79108361a2695f82a224dfd98149716f0348d13e8e5d",
        "resource_type":  "image",
        "mime_type":  "image/jpeg",
        "title":  "a5552b423_3",
        "alt_text":  "William Taylor storefront image",
        "decorative":  false,
        "rights":  "Client supplied and licensed for production",
        "usage":  "Current approved storefront imagery",
        "future_domain":  "reserved",
        "provider_suffix":  "images/storefront-a5552b423-3",
        "required":  true,
        "factory_version":  "william-taylor-factory-v1"
    },
    {
        "logical_key":  "storefront-b079734c1-image",
        "source_kind":  "local",
        "source":  "public/website/images/b079734c1_image.jpg",
        "sha256":  "3d799e84c1d6bbcdc15aa33fad6f80ccd6981f6e1f002063adb7eeaff37c5bae",
        "resource_type":  "image",
        "mime_type":  "image/jpeg",
        "title":  "b079734c1_image",
        "alt_text":  "William Taylor storefront image",
        "decorative":  false,
        "rights":  "Client supplied and licensed for production",
        "usage":  "Current approved storefront imagery",
        "future_domain":  "reserved",
        "provider_suffix":  "images/storefront-b079734c1-image",
        "required":  true,
        "factory_version":  "william-taylor-factory-v1"
    },
    {
        "logical_key":  "storefront-b8589561c-image",
        "source_kind":  "local",
        "source":  "public/website/images/b8589561c_image.jpg",
        "sha256":  "238e18a08eb40bb34de1a829128b94a991077c920d030baab8b19bedd3949882",
        "resource_type":  "image",
        "mime_type":  "image/jpeg",
        "title":  "b8589561c_image",
        "alt_text":  "William Taylor storefront image",
        "decorative":  false,
        "rights":  "Client supplied and licensed for production",
        "usage":  "Current approved storefront imagery",
        "future_domain":  "reserved",
        "provider_suffix":  "images/storefront-b8589561c-image",
        "required":  true,
        "factory_version":  "william-taylor-factory-v1"
    },
    {
        "logical_key":  "storefront-b9c0b1bdf-image",
        "source_kind":  "local",
        "source":  "public/website/images/b9c0b1bdf_image.jpg",
        "sha256":  "7ff6a5dd8b1d8d120b25a60a87901f00a42ed145039c9fdee4a28972562ceb67",
        "resource_type":  "image",
        "mime_type":  "image/jpeg",
        "title":  "b9c0b1bdf_image",
        "alt_text":  "William Taylor storefront image",
        "decorative":  false,
        "rights":  "Client supplied and licensed for production",
        "usage":  "Current approved storefront imagery",
        "future_domain":  "reserved",
        "provider_suffix":  "images/storefront-b9c0b1bdf-image",
        "required":  true,
        "factory_version":  "william-taylor-factory-v1"
    },
    {
        "logical_key":  "storefront-c0cb4e750-image",
        "source_kind":  "local",
        "source":  "public/website/images/c0cb4e750_image.jpg",
        "sha256":  "fb35a569ae71cdbfb85a8934344d886904bf04c5a33ff043b928a06154598a6e",
        "resource_type":  "image",
        "mime_type":  "image/jpeg",
        "title":  "c0cb4e750_image",
        "alt_text":  "William Taylor storefront image",
        "decorative":  false,
        "rights":  "Client supplied and licensed for production",
        "usage":  "Current approved storefront imagery",
        "future_domain":  "reserved",
        "provider_suffix":  "images/storefront-c0cb4e750-image",
        "required":  true,
        "factory_version":  "william-taylor-factory-v1"
    },
    {
        "logical_key":  "storefront-c37b38a71-image",
        "source_kind":  "local",
        "source":  "public/website/images/c37b38a71_image.jpg",
        "sha256":  "e1cf8e83ed13897a3017fd0b76255313da963666e401a81035bf13af0e4c8017",
        "resource_type":  "image",
        "mime_type":  "image/jpeg",
        "title":  "c37b38a71_image",
        "alt_text":  "William Taylor storefront image",
        "decorative":  false,
        "rights":  "Client supplied and licensed for production",
        "usage":  "Current approved storefront imagery",
        "future_domain":  "reserved",
        "provider_suffix":  "images/storefront-c37b38a71-image",
        "required":  true,
        "factory_version":  "william-taylor-factory-v1"
    },
    {
        "logical_key":  "storefront-c54010737-generated-image",
        "source_kind":  "local",
        "source":  "public/website/images/c54010737_generated_image.png",
        "sha256":  "c2317d56cc43585ddea0450d2a2968a27105bad2edef1f465fdab3f94af8cbc5",
        "resource_type":  "image",
        "mime_type":  "image/png",
        "title":  "c54010737_generated_image",
        "alt_text":  "William Taylor storefront image",
        "decorative":  false,
        "rights":  "Client supplied and licensed for production",
        "usage":  "Current approved storefront imagery",
        "future_domain":  "reserved",
        "provider_suffix":  "images/storefront-c54010737-generated-image",
        "required":  true,
        "factory_version":  "william-taylor-factory-v1"
    },
    {
        "logical_key":  "storefront-cf030fe26-iconlight",
        "source_kind":  "local",
        "source":  "public/website/images/cf030fe26_ICONlight.png",
        "sha256":  "303ff0b7ab3d9317eba5d66e41d0b8d4f882ac54348d05c4129e3f9f9485a7e8",
        "resource_type":  "image",
        "mime_type":  "image/png",
        "title":  "cf030fe26_ICONlight",
        "alt_text":  "William Taylor storefront image",
        "decorative":  false,
        "rights":  "Client supplied and licensed for production",
        "usage":  "Current approved storefront imagery",
        "future_domain":  "reserved",
        "provider_suffix":  "images/storefront-cf030fe26-iconlight",
        "required":  true,
        "factory_version":  "william-taylor-factory-v1"
    },
    {
        "logical_key":  "storefront-da608a583-image",
        "source_kind":  "local",
        "source":  "public/website/images/da608a583_image.jpg",
        "sha256":  "f07d9514b6b6608ce095cd0891ab92500b9f35d7b24ce7c0bfc900169828e280",
        "resource_type":  "image",
        "mime_type":  "image/jpeg",
        "title":  "da608a583_image",
        "alt_text":  "William Taylor storefront image",
        "decorative":  false,
        "rights":  "Client supplied and licensed for production",
        "usage":  "Current approved storefront imagery",
        "future_domain":  "reserved",
        "provider_suffix":  "images/storefront-da608a583-image",
        "required":  true,
        "factory_version":  "william-taylor-factory-v1"
    },
    {
        "logical_key":  "storefront-db23eed31-image",
        "source_kind":  "local",
        "source":  "public/website/images/db23eed31_image.jpg",
        "sha256":  "c5d08e2a279d94de73a62eac962c7926578e7c975e377636c1d145a1df35c7ce",
        "resource_type":  "image",
        "mime_type":  "image/jpeg",
        "title":  "db23eed31_image",
        "alt_text":  "William Taylor storefront image",
        "decorative":  false,
        "rights":  "Client supplied and licensed for production",
        "usage":  "Current approved storefront imagery",
        "future_domain":  "reserved",
        "provider_suffix":  "images/storefront-db23eed31-image",
        "required":  true,
        "factory_version":  "william-taylor-factory-v1"
    },
    {
        "logical_key":  "storefront-eab6bab5d-bg",
        "source_kind":  "local",
        "source":  "public/website/images/eab6bab5d_bg.jpg",
        "sha256":  "f307aaf2e002ba14cd1abdf4b33356ec9a789478869fcff36ff8b40d29c773c0",
        "resource_type":  "image",
        "mime_type":  "image/jpeg",
        "title":  "eab6bab5d_bg",
        "alt_text":  "William Taylor storefront image",
        "decorative":  false,
        "rights":  "Client supplied and licensed for production",
        "usage":  "Current approved storefront imagery",
        "future_domain":  "reserved",
        "provider_suffix":  "images/storefront-eab6bab5d-bg",
        "required":  true,
        "factory_version":  "william-taylor-factory-v1"
    },
    {
        "logical_key":  "storefront-ebe8fd1d1-image",
        "source_kind":  "local",
        "source":  "public/website/images/ebe8fd1d1_image.jpg",
        "sha256":  "022bacff2d953f46ce5aee47c80d1139beef98ae815df9c7766a7799170bc727",
        "resource_type":  "image",
        "mime_type":  "image/jpeg",
        "title":  "ebe8fd1d1_image",
        "alt_text":  "William Taylor storefront image",
        "decorative":  false,
        "rights":  "Client supplied and licensed for production",
        "usage":  "Current approved storefront imagery",
        "future_domain":  "reserved",
        "provider_suffix":  "images/storefront-ebe8fd1d1-image",
        "required":  true,
        "factory_version":  "william-taylor-factory-v1"
    },
    {
        "logical_key":  "storefront-ee86da3ae-image",
        "source_kind":  "local",
        "source":  "public/website/images/ee86da3ae_image.jpg",
        "sha256":  "b933126a32b009bf411bc04b1769047ef499dd13d7c1acf847ccffc2d79c790e",
        "resource_type":  "image",
        "mime_type":  "image/jpeg",
        "title":  "ee86da3ae_image",
        "alt_text":  "William Taylor storefront image",
        "decorative":  false,
        "rights":  "Client supplied and licensed for production",
        "usage":  "Current approved storefront imagery",
        "future_domain":  "reserved",
        "provider_suffix":  "images/storefront-ee86da3ae-image",
        "required":  true,
        "factory_version":  "william-taylor-factory-v1"
    },
    {
        "logical_key":  "storefront-fec1e30ee-generated-image",
        "source_kind":  "local",
        "source":  "public/website/images/fec1e30ee_generated_image.png",
        "sha256":  "7d7c71a9fff2dc0ac19528d62b682626e5b20ba54e152fa974bb6a6a5423b9bc",
        "resource_type":  "image",
        "mime_type":  "image/png",
        "title":  "fec1e30ee_generated_image",
        "alt_text":  "William Taylor storefront image",
        "decorative":  false,
        "rights":  "Client supplied and licensed for production",
        "usage":  "Current approved storefront imagery",
        "future_domain":  "reserved",
        "provider_suffix":  "images/storefront-fec1e30ee-generated-image",
        "required":  true,
        "factory_version":  "william-taylor-factory-v1"
    },
    {
        "logical_key":  "storefront-video-1",
        "source_kind":  "remote",
        "source":  "https://media.base44.com/videos/public/6a4d9ad469285a7e6df866f1/2eaa51040_3333.mp4",
        "sha256":  null,
        "resource_type":  "video",
        "mime_type":  "video/mp4",
        "title":  "Storefront video 1",
        "alt_text":  "",
        "decorative":  true,
        "rights":  "Client supplied and licensed for production",
        "usage":  "Current approved storefront video",
        "future_domain":  "reserved",
        "provider_suffix":  "videos/storefront-video-1",
        "required":  false,
        "factory_version":  "william-taylor-factory-v1",
        "allowed_host":  "media.base44.com",
        "max_bytes":  104857600,
        "max_duration_ms":  120000,
        "state":  "deferred-until-explicit-verified-transfer"
    },
    {
        "logical_key":  "storefront-video-2",
        "source_kind":  "remote",
        "source":  "https://media.base44.com/videos/public/6a4d9ad469285a7e6df866f1/eb1f94bda_SnapInsta-Ai_3923038057139474583_77059721635.mp4",
        "sha256":  null,
        "resource_type":  "video",
        "mime_type":  "video/mp4",
        "title":  "Storefront video 2",
        "alt_text":  "",
        "decorative":  true,
        "rights":  "Client supplied and licensed for production",
        "usage":  "Current approved storefront video",
        "future_domain":  "reserved",
        "provider_suffix":  "videos/storefront-video-2",
        "required":  false,
        "factory_version":  "william-taylor-factory-v1",
        "allowed_host":  "media.base44.com",
        "max_bytes":  104857600,
        "max_duration_ms":  120000,
        "state":  "deferred-until-explicit-verified-transfer"
    }
]
JSON, true, 512, JSON_THROW_ON_ERROR),
];
