<div class="cms-site-content" x-on:open-site-content-preview.window="window.open($event.detail.url, '_blank', 'noopener')">
    @once
        <style>
            .cms-site-content{display:grid;gap:1.25rem}.cms-site-content .admin-panel{display:grid;align-content:start;gap:1rem;height:auto}.cms-site-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));align-items:start;gap:1rem}.cms-site-content label,.cms-control{display:grid;gap:.45rem;min-width:0;font-weight:650}.cms-site-content input:not([type=checkbox]):not([type=radio]),.cms-site-content select,.cms-site-content textarea{box-sizing:border-box;display:block;width:100%;min-height:2.85rem;padding:.72rem .85rem;border:1px solid #817a6d;border-radius:.2rem;background:#fff;color:#201d19;font:inherit}.cms-site-content textarea{min-height:7.5rem;resize:vertical}.cms-site-content input:focus-visible,.cms-site-content select:focus-visible,.cms-site-content textarea:focus-visible{outline:3px solid rgba(139,92,35,.3);outline-offset:2px;border-color:#6f481d}.cms-repeat-row{display:grid;grid-template-columns:minmax(9rem,.7fr) minmax(16rem,2fr) minmax(10rem,1fr) auto;align-items:end;gap:.8rem;padding:1rem;border:1px solid #d3ccbf}.cms-site-content fieldset{min-width:0}.admin-media-picker{display:grid;gap:.8rem}.admin-media-picker legend{margin-bottom:.4rem;font-weight:700}.admin-media-picker-grid{margin-top:.2rem}.cms-form-actions,.cms-workflow-actions,.cms-schedule-controls{display:flex;flex-wrap:wrap;align-items:end;gap:.75rem}.cms-schedule-controls{display:grid;grid-template-columns:minmax(18rem,1fr) auto;padding-top:1rem;border-top:1px solid #ded9cd}.cms-timezone{display:block;font-size:.82rem;font-weight:400;color:#655f55}.cms-change-list,.cms-timeline{display:grid;gap:.75rem;margin:0;padding:0;list-style:none}.cms-change-list li,.cms-timeline li{display:grid;gap:.25rem;padding:.85rem 1rem;border-left:3px solid #8b5c23;background:#faf8f3}.cms-timeline small{display:block;color:#655f55}.cms-workflow-group{display:grid;gap:.75rem;padding-top:.25rem}.cms-workflow-group h3{margin:0;font-size:1rem}.cms-danger-zone{padding-top:1rem;border-top:1px solid #d7b7b7}@media(max-width:800px){.cms-site-grid,.cms-repeat-row,.cms-schedule-controls{grid-template-columns:1fr}.cms-form-actions,.cms-workflow-actions{display:grid}.cms-form-actions>*,.cms-workflow-actions>*{width:100%}}
        </style>
    @endonce
    @php($state = $siteContent->publicationState)
    @php($candidateState = $state?->candidate_state?->value)
    <div class="admin-feedback {{ $feedbackType === 'error' ? 'is-error' : '' }}" role="status" aria-live="assertive" tabindex="-1" @if(!$feedback) hidden @endif>{{ $feedback }}</div>

    <section class="admin-panel">
        <div class="cms-page-summary"><div><span class="admin-badge">{{ $candidateState === 'in_review' ? 'In review' : ($candidateState === 'approved' ? 'Approved' : ($candidateState === 'scheduled' ? 'Scheduled' : ($state?->current_public_revision_id ? 'Published' : 'Draft'))) }}</span><h2>{{ $siteContent->title }}</h2><p>{{ $definition->description }}</p>@unless(config('public_site_content.enabled'))<p class="admin-warning"><strong>Website publishing is currently paused.</strong> You can continue preparing and reviewing changes.</p>@endunless</div>
            <dl class="admin-definition-grid"><div><dt>Content type</dt><dd>{{ $definition->label }}</dd></div><div><dt>Draft version</dt><dd>{{ $siteContent->currentDraftRevision->revision_number }}</dd></div><div><dt>Version in review</dt><dd>{{ $state?->candidateRevision?->revision_number ?? 'None' }}</dd></div><div><dt>Published version</dt><dd>{{ $state?->currentPublicRevision?->revision_number ?? 'None' }}</dd></div></dl>
        </div>
        @can($definition->permission('preview'))<button type="button" class="admin-secondary-button" wire:click="preview">Secure preview</button>@endcan
    </section>

    @if($siteContent->type === 'primary_navigation')
        <section class="admin-panel"><h2>Primary navigation</h2><p>Maximum depth two. Use the Move up and Move down buttons as the keyboard-accessible reorder control.</p>
            @foreach($content['items'] as $index => $item)
                <fieldset class="cms-repeat-card"><legend>Item {{ $index + 1 }}</legend>
                    <label>Stable key<input wire:model="content.items.{{ $index }}.key"></label><label>Label<input wire:model="content.items.{{ $index }}.label"></label>
                    <label>Link type<select wire:model="content.items.{{ $index }}.link.type"><option value="internal_path">Internal path</option><option value="external_url">External HTTPS URL</option></select></label><label>Link value<input wire:model="content.items.{{ $index }}.link.value"></label>
                    <label>Visibility<select wire:model="content.items.{{ $index }}.visibility"><option value="all">All</option><option value="desktop">Desktop</option><option value="mobile">Mobile</option></select></label><label><input type="checkbox" wire:model="content.items.{{ $index }}.new_tab"> Open in new tab</label>
                    <div class="admin-page-actions"><button type="button" wire:click="movePrimaryItem({{ $index }},-1)">Move up</button><button type="button" wire:click="movePrimaryItem({{ $index }},1)">Move down</button><button type="button" wire:click="addPrimaryChild({{ $index }})">Add child</button><button type="button" wire:click="removePrimaryItem({{ $index }})">Remove</button></div>
                    @foreach($item['children'] as $childIndex => $child)<fieldset><legend>Child {{ $childIndex + 1 }}</legend><label>Stable key<input wire:model="content.items.{{ $index }}.children.{{ $childIndex }}.key"></label><label>Label<input wire:model="content.items.{{ $index }}.children.{{ $childIndex }}.label"></label><label>Link type<select wire:model="content.items.{{ $index }}.children.{{ $childIndex }}.link.type"><option value="internal_path">Internal path</option><option value="external_url">External HTTPS URL</option></select></label><label>Link value<input wire:model="content.items.{{ $index }}.children.{{ $childIndex }}.link.value"></label></fieldset>@endforeach
                </fieldset>
            @endforeach
            <button type="button" class="admin-secondary-button" wire:click="addPrimaryItem">Add primary item</button>
        </section>
    @elseif($siteContent->type === 'footer_navigation')
        <section class="admin-panel"><h2>Footer navigation</h2>
            @foreach($content['groups'] as $groupIndex => $group)<fieldset class="cms-repeat-card"><legend>{{ $group['label'] }}</legend><label>Business label<input wire:model="content.groups.{{ $groupIndex }}.label"></label>
                @foreach($group['links'] as $linkIndex => $link)<div class="cms-repeat-row"><label>Stable key<input wire:model="content.groups.{{ $groupIndex }}.links.{{ $linkIndex }}.key"></label><label>Label<input wire:model="content.groups.{{ $groupIndex }}.links.{{ $linkIndex }}.label"></label><label>Type<select wire:model="content.groups.{{ $groupIndex }}.links.{{ $linkIndex }}.link.type"><option value="internal_path">Internal</option><option value="external_url">External HTTPS</option></select></label><label>Value<input wire:model="content.groups.{{ $groupIndex }}.links.{{ $linkIndex }}.link.value"></label><button type="button" wire:click="removeFooterLink({{ $groupIndex }},{{ $linkIndex }})">Remove</button></div>@endforeach
                <button type="button" wire:click="addFooterLink({{ $groupIndex }})">Add link</button></fieldset>@endforeach
        </section>
    @elseif($siteContent->type === 'announcement')
        <section class="admin-panel"><h2>Announcement content</h2><p>Plain text only. Schedules that overlap another active announcement are blocked.</p>
            <label>Public message<textarea wire:model="content.message"></textarea></label><label>CTA label<input wire:model="content.cta_label"></label><label>CTA type<select wire:model="content.cta.type"><option value="internal_path">Internal path</option><option value="external_url">External HTTPS URL</option></select></label><label>CTA value<input wire:model="content.cta.value"></label><label>Variant<select wire:model="content.variant"><option value="neutral">Neutral</option><option value="accent">Accent</option><option value="urgent">Urgent</option></select></label><label><input type="checkbox" wire:model="content.dismissible"> Dismissible</label><label>Priority<input type="number" min="0" max="100" wire:model="content.priority"></label><label>Accessibility label<input wire:model="content.accessibility_label"></label>
        </section>
    @elseif($siteContent->type === 'site_profile')
        <div class="cms-site-grid"><section class="admin-panel"><h2>Brand</h2><label>Public brand name<input wire:model="content.brand.name"></label><label>Short description<textarea wire:model="content.brand.description"></textarea></label><label>Copyright holder<input wire:model="content.brand.copyright_holder"></label><x-admin.ready-media-selector label="Header logo" model="content.brand.header_logo_id" :assets="$readyMedia" :current="$content['brand']['header_logo_id']" /><x-admin.ready-media-selector label="Footer logo" model="content.brand.footer_logo_id" :assets="$readyMedia" :current="$content['brand']['footer_logo_id']" /></section>
        <section class="admin-panel"><h2>Contact</h2><label>Public email<input type="email" wire:model="content.contact.email"></label><label>Telephone<input wire:model="content.contact.telephone"></label><label>WhatsApp number<input wire:model="content.contact.whatsapp"></label><p class="cms-help">Use international format, for example +255…</p><label>Physical address<textarea wire:model="content.contact.address"></textarea></label><label>Business hours<textarea wire:model="content.contact.business_hours"></textarea></label><label>Contact button label<input wire:model="content.contact.cta_label"></label></section></div>
        <section class="admin-panel"><h2>Social links</h2>@foreach($content['social_links'] as $index => $social)<div class="cms-repeat-row"><label>Platform<select wire:model="content.social_links.{{ $index }}.platform">@foreach(['instagram','facebook','x','linkedin','youtube','tiktok','pinterest'] as $platform)<option value="{{ $platform }}">{{ ucfirst($platform) }}</option>@endforeach</select></label><label>HTTPS URL<input wire:model="content.social_links.{{ $index }}.url"></label><label>Accessible label<input wire:model="content.social_links.{{ $index }}.label"></label><button type="button" wire:click="removeSocial({{ $index }})">Remove</button></div>@endforeach<button type="button" wire:click="addSocial">Add social link</button></section>
        <section class="admin-panel"><h2>Footer</h2><label>Description<textarea wire:model="content.footer.description"></textarea></label><label>Copyright text<input wire:model="content.footer.copyright"></label><label>Newsletter heading<input wire:model="content.footer.newsletter_heading"></label><label>Newsletter supporting copy<textarea wire:model="content.footer.newsletter_copy"></textarea></label><x-admin.ready-media-selector label="Footer image" model="content.footer.footer_image_id" :assets="$readyMedia" :current="$content['footer']['footer_image_id']" /><p class="cms-help">Newsletter signup collection will be available in a later update. These fields control presentation copy only.</p></section>
    @endif

    @can($definition->permission('edit'))<section class="admin-panel"><h2>Save draft</h2><label>Change description<textarea wire:model="changeSummary" placeholder="Briefly describe what changed"></textarea></label><div class="cms-form-actions"><button type="button" class="admin-primary-button" wire:click="save">Save draft</button></div></section>@endcan

    <section class="admin-panel"><h2>Review and publish</h2>
        @if(in_array($candidateState, [null, 'changes_requested', 'in_review', 'approved'], true))<label>Review note<textarea wire:model="workflowNote" placeholder="Add context for reviewers"></textarea></label>@endif
        @if($state?->candidate_revision_id)<label><input type="checkbox" wire:model="confirmSupersession"> Replace the version currently in review</label>@endif
        <div class="cms-workflow-group"><h3>Workflow</h3><div class="cms-workflow-actions">
            @can($definition->permission('edit'))@if($candidateState !== 'scheduled')<button class="admin-primary-button" type="button" wire:click="submit">Submit for review</button>@endif @endcan
            @can($definition->permission('review'))@if(in_array($candidateState, ['in_review','approved'], true))<button class="admin-secondary-button" type="button" wire:click="requestChanges">Request changes</button>@endif @endcan
            @can($definition->permission('approve'))@if($candidateState === 'in_review')<button class="admin-primary-button" type="button" wire:click="approve">Approve</button>@endif @endcan
            @can($definition->permission('publish'))@if($candidateState === 'approved')<button class="admin-primary-button" type="button" wire:click="publish">Publish now</button>@endif @endcan
            @can($definition->permission('schedule'))@if($candidateState === 'scheduled')<button class="admin-secondary-button" type="button" wire:click="cancelSchedule">Cancel schedule</button>@endif @endcan
        </div></div>
        @can($definition->permission('schedule'))@if($candidateState === 'approved')<div class="cms-schedule-controls"><label>Schedule publication<span class="cms-timezone">Africa/Dar es Salaam</span><input type="datetime-local" wire:model="scheduleLocal"></label><button type="button" class="admin-secondary-button" wire:click="schedule">Schedule approved version</button></div>@endif @endcan
        @if($candidateState === 'scheduled' || $state?->current_public_revision_id)<div class="cms-danger-zone"><label>Reason for high-impact action<textarea wire:model="reason"></textarea></label><div class="cms-workflow-actions">@can($definition->permission('unpublish'))@if($state?->current_public_revision_id)<button class="admin-danger-button" type="button" wire:click="unpublish">Unpublish</button>@endif @endcan</div></div>@endif
        @if($siteContent->type === 'announcement')<div class="admin-page-actions">@can('announcements.archive')<button type="button" wire:click="archive">Archive</button>@endcan @can('announcements.restore')<button type="button" wire:click="restore">Restore</button>@endcan</div>@endif
    </section>

    <section class="admin-panel"><h2>Review changes</h2><ul class="cms-change-list">@forelse($comparison as $change)<li>{{ match($change['field']) {'brand' => 'Brand information changed', 'footer' => 'Footer content changed', 'contact' => 'Contact information changed', 'social_links' => 'Social links changed', default => str($change['field'])->replace('_', ' ')->ucfirst().' changed'} }}</li>@empty<li>No content differences.</li>@endforelse</ul></section>
    <section class="admin-panel"><h2>Version history</h2><ol class="cms-timeline">@foreach($siteContent->revisions->sortByDesc('revision_number') as $revision)<li><div><strong>Version {{ $revision->revision_number }}</strong> <span class="admin-badge">{{ $state?->current_public_revision_id === $revision->id ? 'Published' : ($state?->candidate_revision_id === $revision->id ? str($candidateState)->replace('_', ' ')->title() : ($siteContent->current_draft_revision_id === $revision->id ? 'Draft' : 'Previous')) }}</span></div><span>{{ $revision->change_summary ?: 'No change description provided.' }}</span><small>{{ $revision->author?->name ?? 'Unknown author' }} · {{ $revision->created_at->timezone('Africa/Dar_es_Salaam')->format('d M Y, H:i T') }}</small></li>@endforeach</ol></section>
    <section class="admin-panel"><h2>Publishing history</h2><ol class="cms-timeline">@forelse($state?->transitions?->sortByDesc('occurred_at') ?? [] as $transition)<li><strong>{{ str_replace('_', ' ', ucfirst($transition->to_state)) }}</strong><span>{{ $transition->note ?? $transition->reason }}</span><small>{{ $transition->actor?->name }} - {{ $transition->occurred_at->timezone('Africa/Dar_es_Salaam')->format('Y-m-d H:i T') }}</small></li>@empty<li>No publishing activity.</li>@endforelse</ol></section>
</div>
