<div class="cms-site-content" x-on:open-site-content-preview.window="window.open($event.detail.url, '_blank', 'noopener')">
    @php($state = $siteContent->publicationState)
    @php($candidateState = $state?->candidate_state?->value)
    <div class="admin-feedback {{ $feedbackType === 'error' ? 'is-error' : '' }}" role="status" aria-live="assertive" tabindex="-1" @if(!$feedback) hidden @endif>{{ $feedback }}</div>

    <section class="admin-panel">
        <div class="cms-page-summary"><div><span class="admin-badge">{{ $candidateState ? str_replace('_', ' ', ucfirst($candidateState)) : ($state?->current_public_revision_id ? 'Published' : 'Draft') }}</span><h2>{{ $siteContent->title }}</h2><p>{{ $definition->description }}</p><p><strong>{{ config('public_site_content.enabled') ? 'Public storefront projection is enabled for global Site Content.' : 'Public storefront projection is disabled by environment configuration.' }}</strong></p></div>
            <dl class="admin-definition-grid"><div><dt>Type</dt><dd>{{ $definition->label }}</dd></div><div><dt>Draft</dt><dd>{{ $siteContent->currentDraftRevision->revision_number }}</dd></div><div><dt>Candidate</dt><dd>{{ $state?->candidateRevision?->revision_number ?? 'None' }}</dd></div><div><dt>Designated published</dt><dd>{{ $state?->currentPublicRevision?->revision_number ?? 'None' }}</dd></div></dl>
        </div>
        @can($definition->permission('preview'))<button type="button" class="admin-secondary-button" wire:click="preview">Secure preview</button>@endcan
    </section>

    @if($siteContent->type === 'primary_navigation')
        <section class="admin-panel"><h2>Primary navigation</h2><p>Maximum depth two. Use the Move up and Move down buttons as the keyboard-accessible reorder control.</p>
            @foreach($content['items'] as $index => $item)
                <fieldset class="cms-repeat-card"><legend>Item {{ $index + 1 }}</legend>
                    <label>Stable key<input wire:model="content.items.{{ $index }}.key"></label><label>Label<input wire:model="content.items.{{ $index }}.label"></label>
                    <label>Link type<select wire:model="content.items.{{ $index }}.link.type"><option value="internal_path">Internal path</option><option value="external_url">External HTTPS URL</option></select></label><label>Link value<input wire:model="content.items.{{ $index }}.link.value"></label>
                    <label>Visibility<select wire:model="content.items.{{ $index }}.visibility"><option value="all">All</option><option value="desktop">Desktop</option><option value="mobile">Mobile</option></select></label><label><input type="checkbox" wire:model="content.items.{{ $index }}.new_tab"> Open in new tab</label>
                    <div class="admin-page-actions"><button type="button" wire:click="movePrimaryItem({{ $index }},-1)">Move up</button><button type="button" wire:click="movePrimaryItem({{ $index }},1)">Move down</button><button type="button" wire:click="addPrimaryChild({{ $index }})">Add child</button><button type="button" wire:click="removePrimaryItem({{ $index }})">Remove</button></div>
                    @foreach($item['children'] as $childIndex => $child)<fieldset><legend>Child {{ $childIndex + 1 }}</legend><label>Stable key<input wire:model="content.items.{{ $index }}.children.{{ $childIndex }}.key"></label><label>Label<input wire:model="content.items.{{ $index }}.children.{{ $childIndex }}.label"></label><label>Link type<select wire:model="content.items.{{ $index }}.children.{{ $childIndex }}.link.type"><option value="internal_path">Internal path</option><option value="external_url">External HTTPS URL</option></select></label><label>Link value<input wire:model="content.items.{{ $index }}.children.{{ $childIndex }}.link.value"></label></fieldset>@endforeach
                </fieldset>
            @endforeach
            <button type="button" class="admin-secondary-button" wire:click="addPrimaryItem">Add primary item</button>
        </section>
    @elseif($siteContent->type === 'footer_navigation')
        <section class="admin-panel"><h2>Footer navigation</h2>
            @foreach($content['groups'] as $groupIndex => $group)<fieldset class="cms-repeat-card"><legend>{{ $group['label'] }}</legend><label>Business label<input wire:model="content.groups.{{ $groupIndex }}.label"></label>
                @foreach($group['links'] as $linkIndex => $link)<div class="cms-repeat-row"><label>Stable key<input wire:model="content.groups.{{ $groupIndex }}.links.{{ $linkIndex }}.key"></label><label>Label<input wire:model="content.groups.{{ $groupIndex }}.links.{{ $linkIndex }}.label"></label><label>Type<select wire:model="content.groups.{{ $groupIndex }}.links.{{ $linkIndex }}.link.type"><option value="internal_path">Internal</option><option value="external_url">External HTTPS</option></select></label><label>Value<input wire:model="content.groups.{{ $groupIndex }}.links.{{ $linkIndex }}.link.value"></label><button type="button" wire:click="removeFooterLink({{ $groupIndex }},{{ $linkIndex }})">Remove</button></div>@endforeach
                <button type="button" wire:click="addFooterLink({{ $groupIndex }})">Add link</button></fieldset>@endforeach
        </section>
    @elseif($siteContent->type === 'announcement')
        <section class="admin-panel"><h2>Announcement content</h2><p>Plain text only. Schedules that overlap another active announcement are blocked.</p>
            <label>Public message<textarea wire:model="content.message"></textarea></label><label>CTA label<input wire:model="content.cta_label"></label><label>CTA type<select wire:model="content.cta.type"><option value="internal_path">Internal path</option><option value="external_url">External HTTPS URL</option></select></label><label>CTA value<input wire:model="content.cta.value"></label><label>Variant<select wire:model="content.variant"><option value="neutral">Neutral</option><option value="accent">Accent</option><option value="urgent">Urgent</option></select></label><label><input type="checkbox" wire:model="content.dismissible"> Dismissible</label><label>Priority<input type="number" min="0" max="100" wire:model="content.priority"></label><label>Accessibility label<input wire:model="content.accessibility_label"></label>
        </section>
    @elseif($siteContent->type === 'site_profile')
        <div class="cms-site-grid"><section class="admin-panel"><h2>Brand identity</h2><label>Public brand name<input wire:model="content.brand.name"></label><label>Short description<textarea wire:model="content.brand.description"></textarea></label><label>Copyright holder<input wire:model="content.brand.copyright_holder"></label><label>Header logo Media ULID<input wire:model="content.brand.header_logo_id"></label><label>Footer logo Media ULID<input wire:model="content.brand.footer_logo_id"></label></section>
        <section class="admin-panel"><h2>Contact and WhatsApp</h2><label>Public email<input type="email" wire:model="content.contact.email"></label><label>Telephone<input wire:model="content.contact.telephone"></label><label>WhatsApp E.164 number<input wire:model="content.contact.whatsapp"></label><label>Physical address<textarea wire:model="content.contact.address"></textarea></label><label>Business hours<textarea wire:model="content.contact.business_hours"></textarea></label><label>Contact CTA label<input wire:model="content.contact.cta_label"></label></section></div>
        <section class="admin-panel"><h2>Social links</h2>@foreach($content['social_links'] as $index => $social)<div class="cms-repeat-row"><label>Platform<select wire:model="content.social_links.{{ $index }}.platform">@foreach(['instagram','facebook','x','linkedin','youtube','tiktok','pinterest'] as $platform)<option value="{{ $platform }}">{{ ucfirst($platform) }}</option>@endforeach</select></label><label>HTTPS URL<input wire:model="content.social_links.{{ $index }}.url"></label><label>Accessible label<input wire:model="content.social_links.{{ $index }}.label"></label><button type="button" wire:click="removeSocial({{ $index }})">Remove</button></div>@endforeach<button type="button" wire:click="addSocial">Add social link</button></section>
        <section class="admin-panel"><h2>Footer copy and media</h2><label>Description<textarea wire:model="content.footer.description"></textarea></label><label>Copyright text<input wire:model="content.footer.copyright"></label><label>Newsletter heading<input wire:model="content.footer.newsletter_heading"></label><label>Newsletter supporting copy<textarea wire:model="content.footer.newsletter_copy"></textarea></label><label>Footer image Media ULID<input wire:model="content.footer.footer_image_id"></label><p>Newsletter persistence is not implemented.</p></section>
    @endif

    @can($definition->permission('edit'))<section class="admin-panel"><h2>Save immutable draft</h2><label>Change summary<textarea wire:model="changeSummary"></textarea></label><button type="button" class="admin-primary-button" wire:click="save">Save draft</button></section>@endcan

    <section class="admin-panel"><h2>Review and publication</h2><label>Submission or review note<textarea wire:model="workflowNote"></textarea></label><label>High-impact reason<textarea wire:model="reason"></textarea></label>@if($state?->candidate_revision_id)<label><input type="checkbox" wire:model="confirmSupersession"> Confirm candidate supersession</label>@endif
        <div class="admin-page-actions">@can($definition->permission('edit'))<button type="button" wire:click="submit">Submit for review</button>@endcan @can($definition->permission('review'))<button type="button" wire:click="requestChanges">Request changes</button>@endcan @can($definition->permission('approve'))<button type="button" wire:click="approve">Approve candidate</button>@endcan @can($definition->permission('publish'))<button type="button" wire:click="publish">Designate published</button>@endcan @can($definition->permission('schedule'))<button type="button" wire:click="cancelSchedule">Cancel schedule</button>@endcan @can($definition->permission('unpublish'))<button type="button" wire:click="unpublish">Unpublish</button>@endcan</div>
        @can($definition->permission('schedule'))<label>Schedule in Africa/Dar_es_Salaam<input type="datetime-local" wire:model="scheduleLocal"></label><button type="button" wire:click="schedule">Schedule approved revision</button>@endcan
        @if($siteContent->type === 'announcement')<div class="admin-page-actions">@can('announcements.archive')<button type="button" wire:click="archive">Archive</button>@endcan @can('announcements.restore')<button type="button" wire:click="restore">Restore</button>@endcan</div>@endif
    </section>

    <section class="admin-panel"><h2>Typed revision comparison</h2><ul>@forelse($comparison as $change)<li><strong>{{ $change['field'] }}</strong>: {{ $change['change'] }}</li>@empty<li>No semantic differences.</li>@endforelse</ul></section>
    <section class="admin-panel"><h2>Immutable revision history</h2><ol class="cms-timeline">@foreach($siteContent->revisions->sortByDesc('revision_number') as $revision)<li><strong>Revision {{ $revision->revision_number }}</strong><span>{{ $revision->change_summary }}</span><small>{{ $revision->author?->name }} - {{ $revision->created_at->timezone('Africa/Dar_es_Salaam')->format('Y-m-d H:i T') }}</small></li>@endforeach</ol></section>
    <section class="admin-panel"><h2>Publication transition history</h2><ol class="cms-timeline">@forelse($state?->transitions?->sortByDesc('occurred_at') ?? [] as $transition)<li><strong>{{ str_replace('_', ' ', ucfirst($transition->to_state)) }}</strong><span>{{ $transition->note ?? $transition->reason }}</span><small>{{ $transition->actor?->name }} - {{ $transition->occurred_at->timezone('Africa/Dar_es_Salaam')->format('Y-m-d H:i T') }}</small></li>@empty<li>No publication transitions.</li>@endforelse</ol></section>
</div>