<!doctype html>
<html lang="en">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>{{ $siteContent->title }} preview - Revision {{ $revision->revision_number }}</title><style>body{font:16px/1.5 system-ui;margin:0;color:#171717;background:#f5f3ee}.banner{padding:12px 24px;background:#251f1a;color:#fff}.wrap{max-width:1100px;margin:auto;padding:32px}.card{background:#fff;padding:20px;border:1px solid #ddd;border-radius:10px}nav ul{display:flex;flex-wrap:wrap;gap:20px;list-style:none;padding:0}.announcement{text-align:center;padding:16px;background:#e9dfce}.footer-groups{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:20px}@media(max-width:600px){.wrap{padding:18px}nav ul{display:block}}</style></head>
<body><div class="banner">Secure {{ str_replace('_', ' ', $siteContent->type) }} preview - Revision {{ $revision->revision_number }} - Public storefront projection is not active yet.</div><main class="wrap">
@if($siteContent->type === 'primary_navigation')<nav aria-label="Primary preview"><ul>@foreach($revision->payload['items'] as $item)<li><strong>{{ $item['label'] }}</strong>@if($item['children'])<ul>@foreach($item['children'] as $child)<li>{{ $child['label'] }}</li>@endforeach</ul>@endif</li>@endforeach</ul></nav>
@elseif($siteContent->type === 'footer_navigation')<div class="footer-groups">@foreach($revision->payload['groups'] as $group)<section class="card"><h2>{{ $group['label'] }}</h2><ul>@foreach($group['links'] as $link)<li>{{ $link['label'] }}</li>@endforeach</ul></section>@endforeach</div>
@elseif($siteContent->type === 'announcement')<section class="announcement" aria-label="{{ $revision->payload['accessibility_label'] ?: 'Announcement preview' }}"><p>{{ $revision->payload['message'] }}</p>@if($revision->payload['cta_label'])<span>{{ $revision->payload['cta_label'] }}</span>@endif</section>
@elseif($siteContent->type === 'site_profile')<section class="card"><h1>{{ data_get($revision->payload, 'brand.name') }}</h1><p>{{ data_get($revision->payload, 'brand.description') }}</p><h2>Contact</h2><p>{{ data_get($revision->payload, 'contact.email') }}<br>{{ data_get($revision->payload, 'contact.telephone') }}<br>{{ data_get($revision->payload, 'contact.address') }}</p><h2>Social links</h2><ul>@foreach(data_get($revision->payload, 'social_links', []) as $social)<li>{{ $social['label'] }}</li>@endforeach</ul><footer><p>{{ data_get($revision->payload, 'footer.description') }}</p><p>{{ data_get($revision->payload, 'footer.copyright') }}</p></footer></section>
@endif
</main></body></html>