@include('admin.inventory.styles')
@once
<style>
.orders-metrics{grid-template-columns:repeat(5,minmax(0,1fr))}.orders-metrics article{align-content:start}.orders-metrics small{color:#706b60}.orders-filters{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:1rem;align-items:end}.orders-filters label{display:grid;gap:.5rem;font-size:.85rem}.orders-filter-actions{display:flex;gap:.7rem;flex-wrap:wrap;align-items:center}.orders-table{font-size:.85rem}.orders-table th{font-size:.68rem;letter-spacing:.04em}.orders-table .order-identity{width:18%}.orders-table .order-customer{width:19%}.order-badge{display:inline-block;padding:.3rem .5rem;border:1px solid #d9d2c5;background:#f5f2eb;color:#575044;font-size:.75rem;line-height:1.5}.order-badge[data-tone=success]{background:#f2f5ed;border-color:#aab29b;color:#35432d}.order-badge[data-tone=attention],.order-attention{background:#faf4e6;border-color:#c9ad72;color:#71511d}.order-statuses{display:flex;gap:.6rem;flex-wrap:wrap}.order-statuses>span{display:grid;gap:.3rem}.order-statuses small{font-size:.7rem;color:#706b60;text-transform:uppercase;letter-spacing:.08em}.order-columns{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:1.5rem}.order-fields{display:grid;grid-template-columns:minmax(6rem,1fr) minmax(0,2fr);gap:.7rem 1rem;line-height:1.6}.order-fields dt{color:#706b60}.order-fields dd{margin:0;overflow-wrap:anywhere;white-space:pre-line}.order-payment{border-top:1px solid #e5dfd4;padding-top:1.5rem;margin-top:1.5rem}.order-attention{padding:1rem;border:1px solid #c9ad72;line-height:1.6}.order-attention p{margin:.4rem 0}.order-timeline{list-style:none;padding:0;display:grid;gap:0}.order-timeline li{display:grid;grid-template-columns:11rem minmax(0,1fr);gap:1rem;padding:.85rem 0;border-bottom:1px solid #e5dfd4}.order-timeline time{color:#706b60;font-size:.85rem}.order-empty{text-align:center;padding:3rem 1rem}.order-empty p{color:#706b60}.order-totals{max-width:26rem;margin-left:auto}.order-section-heading{display:flex;justify-content:space-between;align-items:center;gap:1rem;flex-wrap:wrap}.order-links{display:flex;gap:.7rem;flex-wrap:wrap;margin-top:.5rem}.inventory-workspace .orders-table td small{font-size:.78rem}
@media(max-width:1200px){.orders-metrics{grid-template-columns:repeat(3,minmax(0,1fr))}.orders-table thead{display:none}.orders-table,.orders-table tbody,.orders-table tr,.orders-table td{display:block;width:auto}.orders-table tr{padding:1rem 0;border-bottom:1px solid #d9d2c5}.orders-table td{display:grid;grid-template-columns:8rem minmax(0,1fr);gap:.75rem;padding:.4rem 0;border:0}.orders-table td::before{content:attr(data-label);color:#706b60;font-size:.75rem;text-transform:uppercase}.orders-table .order-identity,.orders-table .order-customer{width:auto}}
@media(max-width:768px){.order-columns{grid-template-columns:minmax(0,1fr)}.orders-filters{grid-template-columns:repeat(2,minmax(0,1fr))}.orders-metrics{grid-template-columns:repeat(2,minmax(0,1fr))}.order-timeline li{grid-template-columns:minmax(0,1fr);gap:.4rem}.orders-table td{grid-template-columns:6rem minmax(0,1fr)}}
@media(max-width:480px){.orders-filters,.orders-metrics{grid-template-columns:minmax(0,1fr)}.order-fields{grid-template-columns:minmax(0,1fr);gap:.3rem}.order-fields dd{margin-bottom:.7rem}}
</style>
@endonce
