<x-admin.layout :title="$order->order_number" description="Review and progress a protected demonstration customer Order.">
    @if(session('status'))<div class="admin-feedback" role="status">{{ session('status') }}</div>@endif
    @if($errors->any())<div class="admin-feedback is-error" role="alert">{{ $errors->first() }}</div>@endif
    <div class="admin-section-heading"><p>Demo Order</p><h1>{{ $order->order_number }}</h1><p>Not a production Pricing, Inventory, payment or accounting record.</p></div>
    <section class="admin-panel"><h2>Summary</h2><dl class="admin-definition-grid"><div><dt>Created</dt><dd>{{ $order->created_at->format('Y-m-d H:i T') }}</dd></div><div><dt>Status</dt><dd>{{ str($order->status->value)->replace('_',' ')->title() }}</dd></div><div><dt>Manual payment</dt><dd>{{ str($order->payment_status->value)->replace('_',' ')->title() }}</dd></div><div><dt>Total</dt><dd>{{ \App\Domain\Orders\Support\OrderMoney::format($order->total_minor,$order->currency) }}</dd></div></dl></section>
    <section class="admin-panel"><h2>Customer and delivery</h2><p>{{ $order->customer_name }}<br>{{ $order->customer_email }}<br>{{ $order->customer_telephone }}</p><p>{!! nl2br(e($order->delivery_address)) !!}</p><p>{{ $order->delivery_instructions ?: 'No delivery instructions.' }}</p></section>
    <section class="admin-panel"><h2>Items</h2><div class="admin-table-wrap"><table><thead><tr><th>Product snapshot</th><th>Variant/SKU</th><th>Quantity</th><th>Unit</th><th>Line total</th></tr></thead><tbody>@foreach($order->items as $item)<tr><td>{{ $item->product_name }}</td><td>{{ $item->variant_name ?: '—' }}<br><small>{{ $item->sku }}</small></td><td>{{ $item->quantity }}</td><td>{{ \App\Domain\Orders\Support\OrderMoney::format($item->unit_amount_minor,$order->currency) }}</td><td>{{ \App\Domain\Orders\Support\OrderMoney::format($item->line_total_minor,$order->currency) }}</td></tr>@endforeach</tbody></table></div></section>
    <section class="admin-panel"><h2>Operations</h2><div class="admin-page-actions">
        @foreach($order->status->next() as $next)@php($permission=match($next){\App\Domain\Orders\Enums\OrderStatus::Confirmed=>'orders.confirm',\App\Domain\Orders\Enums\OrderStatus::InPreparation=>'orders.prepare',\App\Domain\Orders\Enums\OrderStatus::Ready=>'orders.mark-ready',\App\Domain\Orders\Enums\OrderStatus::Dispatched=>'orders.dispatch',\App\Domain\Orders\Enums\OrderStatus::Delivered=>'orders.deliver',\App\Domain\Orders\Enums\OrderStatus::Cancelled=>'orders.cancel',default=>'orders.view'})
        @can($permission)<form method="POST" action="{{ route('admin.orders.transition',$order) }}">@csrf<input type="hidden" name="status" value="{{ $next->value }}"><input type="hidden" name="lock_version" value="{{ $order->lock_version }}">@if($next===\App\Domain\Orders\Enums\OrderStatus::Cancelled)<label>Cancellation reason<input required name="reason"></label>@endif<button class="{{ $next===\App\Domain\Orders\Enums\OrderStatus::Cancelled?'admin-secondary-button':'admin-primary-button' }}">{{ str($next->value)->replace('_',' ')->title() }}</button></form>@endcan @endforeach
        <a class="admin-secondary-button" target="_blank" href="{{ route('admin.orders.summary',$order) }}">Print Order Summary</a>
        @can('orders.receipts.view')@if($order->payment_status===\App\Domain\Orders\Enums\PaymentStatus::Paid)<a class="admin-secondary-button" target="_blank" href="{{ route('admin.orders.receipt',$order) }}">View Demo Receipt</a>@endif @endcan
    </div></section>
    @can('orders.payment-status.manage')<section class="admin-panel"><h2>Manual demonstration payment status</h2><p>No gateway, settlement, accounting or refund occurs.</p><form method="POST" action="{{ route('admin.orders.payment',$order) }}">@csrf<input type="hidden" name="lock_version" value="{{ $order->lock_version }}"><label>Status<select name="payment_status"><option value="unpaid">Unpaid</option><option value="partially_paid">Partially paid</option><option value="paid">Paid</option><option disabled>Refunded — unavailable</option></select></label><label>Internal reason<input required name="payment_reason"></label><button class="admin-primary-button">Update manual status</button></form></section>@endcan
    @can('orders.notes.create')<section class="admin-panel"><h2>Internal notes</h2><form method="POST" action="{{ route('admin.orders.notes.store',$order) }}">@csrf<label>New immutable internal note<textarea required maxlength="2000" name="note"></textarea></label><button class="admin-primary-button">Add internal note</button></form><ul>@forelse($order->notes as $note)<li>{{ $note->note }} — {{ $note->actor->name }}, {{ $note->created_at->format('Y-m-d H:i') }}</li>@empty<li>No internal notes.</li>@endforelse</ul></section>@endcan
    <section class="admin-panel"><h2>Immutable history</h2><ol>@foreach($order->statusEvents as $event)<li>{{ $event->new_status }} — {{ $event->actor->name }} — {{ $event->created_at->format('Y-m-d H:i') }} @if($event->reason)({{ $event->reason }})@endif</li>@endforeach @foreach($order->paymentEvents as $event)<li>Payment: {{ $event->previous_status }} → {{ $event->new_status }} — {{ $event->actor->name }} — {{ $event->created_at->format('Y-m-d H:i') }}</li>@endforeach</ol></section>
</x-admin.layout>
