<x-admin.layout :title="$product->currentDraftRevision?->title ?? 'Product'" description="Edit, validate and save this Product directly." eyebrow="Catalogue" :breadcrumbs="['Products' => route('admin.products.index'), ($product->currentDraftRevision?->title ?? 'Product') => null]">
    @if(session('status'))<div class="admin-panel" role="status">{{ session('status') }}</div>@endif
    @if($errors->any())<div class="admin-panel" role="alert"><strong>Product was not saved.</strong><ul>@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
    @if($product->archived_at)<div class="admin-panel">This Product is archived and read-only.</div>@endif
    @php($primaryCategory = $product->categories->firstWhere('pivot.is_primary', true) ?? $product->categories->first())
    <section class="admin-foundation-banner"><div><span class="admin-status">{{ $product->archived_at ? 'Archived' : ($product->catalogue_status === 'ready' ? 'Active' : 'Hidden') }}</span><h2>{{ $product->currentDraftRevision?->title }}</h2><p>{{ $primaryCategory?->name ?? 'No category yet' }} · {{ $product->variants->whereNull('archived_at')->count() }} Variants · Updated {{ $product->updated_at->diffForHumans() }}</p></div><div class="admin-page-actions">@if($storefrontResolvable)<a class="admin-secondary-button" href="{{ route('products.show', ['product' => $product->slug]) }}" target="_blank" rel="noopener">View storefront</a>@else<span class="admin-field-help">Complete the required Product information before viewing it on the storefront.</span>@endif</div></section>
    <section class="admin-panel" aria-labelledby="storefront-readiness-title"><div class="admin-section-heading"><p>Storefront status</p><h2 id="storefront-readiness-title">{{ $storefrontResolvable ? 'Ready for storefront' : ($product->catalogue_status === 'ready' ? 'Needs attention' : 'Hidden from storefront') }}</h2></div>@if($storefrontReadiness->ready)<p>✓ Price &nbsp; ✓ Primary category &nbsp; ✓ Primary image &nbsp; ✓ Default Variant</p>@else<ul>@foreach($storefrontIssues as $issue)<li>{{ $issue }}</li>@endforeach</ul>@endif</section>
    @include('admin.inventory.product-summary')
    <form method="POST" action="{{ route('admin.products.update', $product) }}">@csrf @method('PUT')
        <input type="hidden" name="lock_version" value="{{ $product->lock_version }}">
        <section class="admin-panel admin-form-grid">
            <div class="admin-section-heading"><p>Product information</p><h2>Storefront content</h2></div>
            <x-admin.field label="Product name" for="product-title" :error="$errors->first('title')"><input id="product-title" name="title" value="{{ old('title', $product->currentDraftRevision?->title) }}" required></x-admin.field>
            <x-admin.field label="Slug" for="product-slug" :help="$product->slug === \App\Domain\Catalogue\Support\OxfordProductPresenter::SLUG ? 'This historic storefront URL is fixed for this Product.' : 'Used in this Product’s storefront URL.'" :error="$errors->first('slug')"><input id="product-slug" name="slug" value="{{ old('slug', $product->slug) }}" required @readonly($product->slug === \App\Domain\Catalogue\Support\OxfordProductPresenter::SLUG)></x-admin.field>
            <x-admin.field label="Short description" for="product-short-description" :error="$errors->first('short_description')"><textarea id="product-short-description" name="short_description" rows="3">{{ old('short_description', $product->currentDraftRevision?->short_description) }}</textarea></x-admin.field>
            <x-admin.field label="Main description" for="product-description" :error="$errors->first('description')"><textarea id="product-description" name="description" rows="8">{{ old('description', strip_tags($product->currentDraftRevision?->description_html ?? '')) }}</textarea></x-admin.field>
            <x-admin.field label="Materials" for="product-materials" :error="$errors->first('materials')"><textarea id="product-materials" name="materials" rows="3">{{ old('materials', $product->currentDraftRevision?->materials) }}</textarea></x-admin.field>
            <x-admin.field label="Fit" for="product-fit" :error="$errors->first('fit')"><textarea id="product-fit" name="fit" rows="3">{{ old('fit', $product->currentDraftRevision?->fit) }}</textarea></x-admin.field>
            <x-admin.field label="Care" for="product-care" :error="$errors->first('care')"><textarea id="product-care" name="care" rows="3">{{ old('care', $product->currentDraftRevision?->care) }}</textarea></x-admin.field>
            <x-admin.field label="Features" for="product-features" help="Enter one feature per line." :error="$errors->first('features')"><textarea id="product-features" name="features" rows="4">{{ old('features', implode("\n", $product->currentDraftRevision?->features ?? [])) }}</textarea></x-admin.field>
        </section>

        <section class="admin-panel admin-form-grid"><div class="admin-section-heading"><p>Pricing</p><h2>Authoritative Product price</h2><p>Variants inherit this price unless an override is entered below.</p></div>
            <label>Currency<select name="currency"><option value="TZS">TZS</option></select></label>
            <label>Base price (TZS)<input name="base_price" inputmode="numeric" value="{{ old('base_price', app(\App\Domain\Catalogue\Support\ProductPrice::class)->majorInput($product->base_price_minor, $product->currency)) }}" required></label>
            <label>Compare-at price (optional)<input name="compare_at_price" inputmode="numeric" value="{{ old('compare_at_price', app(\App\Domain\Catalogue\Support\ProductPrice::class)->majorInput($product->compare_at_price_minor, $product->currency)) }}"></label>
        </section>

        <section class="admin-panel admin-form-grid"><div class="admin-section-heading"><p>Categories & merchandising</p><h2>Storefront classification</h2></div>
            <label>Primary Category<select name="primary_category_id" required><option value="">Choose Category</option>@foreach($categories as $category)<option value="{{ $category->id }}" @selected(old('primary_category_id', $primaryCategory?->id) === $category->id)>{{ $category->parent?->name ? $category->parent->name.' → ' : '' }}{{ $category->name }}</option>@endforeach</select></label>
            <fieldset><legend>Additional Categories</legend>@foreach($categories as $category)<label><input type="checkbox" name="category_ids[]" value="{{ $category->id }}" @checked(in_array($category->id, old('category_ids', $product->categories->pluck('id')->all()), true))> {{ $category->name }}</label>@endforeach</fieldset>
        </section>

        <section class="admin-panel"><div class="admin-section-heading"><p>Media</p><h2>Primary image and gallery</h2><p>Only ready images are shown. Removing an association preserves the Media Asset.</p></div>
            <div class="admin-form-grid">
                <div><h3>Primary image</h3><x-admin.media-picker id="product-primary" name="primary_media_id" :selected="$primarySelected" button-label="Change media" :show-alt="true" :alts="$mediaAlts" /></div>
                <div class="admin-form-wide"><h3>Product gallery</h3><x-admin.media-picker id="product-gallery" name="gallery_media_ids" mode="multiple" :selected="$gallerySelected" button-label="Add images" :show-order="true" :show-alt="true" :orders="$galleryOrders" :alts="$mediaAlts" /></div>
            </div>
        </section>

        @php($activeColourCount = $product->options->firstWhere('key', 'colour')?->values->whereNull('archived_at')->count() ?? 0)
        @php($activeSizeCount = $product->options->firstWhere('key', 'size')?->values->whereNull('archived_at')->count() ?? 0)
        <section class="admin-panel"><div class="admin-section-heading"><p>Variants</p><h2>Sellable combinations</h2><p>A Variant is one sellable combination of this Product's options, such as Black / M.</p><strong>{{ $product->variants->whereNull('archived_at')->count() }} sellable combinations</strong>@if($activeColourCount && $activeSizeCount)<p>{{ $activeColourCount }} Colours × {{ $activeSizeCount }} Sizes</p>@endif<p>Default: {{ $product->defaultVariant?->values?->pluck('label')->join(' / ') ?: 'Not selected' }}</p></div>
            <div class="admin-form-grid"><label>Colours (one per line)<textarea name="colours" rows="5">{{ old('colours', $product->options->firstWhere('key', 'colour')?->values->whereNull('archived_at')->pluck('label')->join("\n")) }}</textarea><small>Colour is optional. Existing values keep their identities.</small></label><label>Sizes (one per line)<textarea name="sizes" rows="5">{{ old('sizes', $product->options->firstWhere('key', 'size')?->values->whereNull('archived_at')->pluck('label')->join("\n")) }}</textarea><small>Size is optional and Product-specific.</small></label><label><input type="checkbox" name="synchronize_variants" value="1"> Update Variants after changing Colours or Sizes</label></div>
            @forelse($product->options as $option)<fieldset class="product-option-values"><legend><strong>{{ $option->label }}</strong></legend>@foreach($option->values as $value)<label><span class="sr-only">{{ $option->label }} name</span><input name="option_labels[{{ $value->id }}]" aria-label="{{ $option->label }} name" value="{{ old('option_labels.'.$value->id, $value->label) }}"></label>@endforeach</fieldset>@empty<p>No options have been configured for this Product.</p>@endforelse
            <p class="admin-field-help">Inactive Variants cannot be selected for purchase. This is not a stock indicator.</p><div class="admin-table-wrap product-variant-table-wrap"><table class="product-variant-table"><thead><tr><th>Variant</th><th>SKU</th><th>Price</th><th>Status</th><th>Default</th></tr></thead><tbody>@forelse($product->variants as $variant)<tr><td data-label="Variant"><strong>{{ $variant->values->sortBy('pivot.product_option_id')->pluck('label')->join(' / ') ?: 'Default' }}</strong></td><td data-label="SKU" class="product-variant-sku"><input name="variant_skus[{{ $variant->id }}]" aria-label="Variant SKU" title="{{ $variant->sku }}" value="{{ old('variant_skus.'.$variant->id, $variant->sku) }}"></td><td data-label="Price" class="product-variant-price"><span>{{ $variant->price_override_minor === null ? 'Uses Product price' : 'TZS override' }}</span><label><span class="sr-only">Optional price override</span><input name="variant_prices[{{ $variant->id }}]" inputmode="numeric" placeholder="Optional override" value="{{ old('variant_prices.'.$variant->id, app(\App\Domain\Catalogue\Support\ProductPrice::class)->majorInput($variant->price_override_minor, $product->currency)) }}"></label></td><td data-label="Status"><span class="admin-status">{{ $variant->archived_at ? 'Inactive' : 'Active' }}</span></td><td data-label="Default" class="product-variant-default"><label><input type="radio" name="default_variant_id" value="{{ $variant->id }}" @checked(old('default_variant_id', $product->default_variant_id) === $variant->id)><span class="sr-only">Make {{ $variant->values->pluck('label')->join(' / ') ?: 'this Variant' }} default</span></label></td></tr>@empty<tr><td colspan="5">No Variants configured. Update Variants to create one sellable default Variant.</td></tr>@endforelse</tbody></table></div>
        </section>

        <section class="admin-panel"><div class="admin-section-heading"><p>Media & colours</p><h2>Colour imagery</h2><p>Select one reusable gallery per Colour. The first selected image is primary for that Colour.</p></div>
            @forelse($colourValues as $colour)<fieldset><legend><strong>{{ $colour->label }}</strong></legend><div class="admin-field"><label for="colour-swatch-{{ $colour->id }}">Swatch</label><div class="product-swatch-control"><input class="product-swatch-picker" id="colour-swatch-{{ $colour->id }}" type="color" value="{{ old('swatch_hex.'.$colour->id, $colour->swatch_hex ?: '#808080') }}" oninput="this.nextElementSibling.value=this.value.toUpperCase()"><input class="product-swatch-hex" name="swatch_hex[{{ $colour->id }}]" maxlength="7" value="{{ old('swatch_hex.'.$colour->id, $colour->swatch_hex ?: '#808080') }}" oninput="if(/^#[0-9a-fA-F]{6}$/.test(this.value)){this.previousElementSibling.value=this.value}"></div>@error('swatch_hex.'.$colour->id)<small class="admin-field-error">{{ $message }}</small>@enderror</div><p class="admin-field-help">This gallery is shared by every {{ $colour->label }} Size Variant.</p><x-admin.media-picker id="colour-media-{{ $colour->id }}" name="colour_media[{{ $colour->id }}]" mode="multiple" :selected="$colourSelected->get($colour->id, [])" button-label="Choose colour images" :show-order="true" order-name="colour_media_order[{{ $colour->id }}]" :orders="$colourOrders->get($colour->id, [])" /></fieldset>@empty<p>Add Colour values and save before assigning colour-specific galleries.</p>@endforelse
        </section>

        <section class="admin-panel"><div class="admin-section-heading"><p>Merchandising</p><h2>Badges and related Products</h2><p>Select up to four Products in display order. Only active catalogue Products are available.</p></div><div class="admin-form-grid">@forelse($relatedCandidates as $candidate)<label><input type="checkbox" name="related_product_ids[]" value="{{ $candidate->id }}" @checked(in_array($candidate->id, old('related_product_ids', $relatedIds), true))> {{ $candidate->currentDraftRevision?->title }}</label>@empty<p>No other active Products are available yet.</p>@endforelse</div><p>NEW is retained as catalogue presentation where already assigned. PRE-ORDER, LIMITED and scarcity claims remain campaign-owned; stock badges remain Inventory-owned.</p></section>
        <section class="admin-panel admin-form-grid"><label>Status<select name="status"><option value="hidden" @selected($product->catalogue_status !== 'ready' && !$product->archived_at)>Hidden</option><option value="active" @selected($product->catalogue_status === 'ready' && !$product->archived_at)>Active</option><option value="archived" @selected($product->archived_at)>Archived</option></select></label>
            <x-admin.form-actions sticky>
                <x-slot:secondary><a class="admin-secondary-button" href="{{ route('admin.products.index') }}">Back to Products</a></x-slot:secondary>
                <x-slot:primary>@can('products.manage')<button class="admin-primary-button" @disabled($product->archived_at)>Save Product</button>@endcan</x-slot:primary>
            </x-admin.form-actions>
        </section>
    </form>
</x-admin.layout>
