<div class="admin-media-detail">
    <div id="media-feedback" aria-live="assertive" role="status" tabindex="-1" x-on:media-replacement-stale.window="$nextTick(() => $el.focus())" class="admin-feedback {{ $feedbackType === 'error' ? 'is-error' : '' }}" @if(!$feedback) hidden @endif>{{ $feedback }}</div>
    <section class="admin-panel admin-media-hero"><div><img src="{{ $previewUrl }}" alt="{{ $this->asset->is_decorative ? '' : $this->asset->default_alt_text }}"></div><dl class="admin-definition-grid"><div><dt>State</dt><dd>{{ $this->asset->state->value }}</dd></div><div><dt>Type</dt><dd>{{ $this->asset->resource_type->value }}</dd></div><div><dt>Dimensions</dt><dd>{{ $this->asset->width }} x {{ $this->asset->height }}</dd></div><div><dt>Usage</dt><dd>{{ $this->asset->usages->count() }}</dd></div><div><dt>Reconciliation</dt><dd>{{ $this->asset->processing_error ?: 'Provider state has no reported reconciliation error.' }}</dd></div></dl></section>
    <section class="admin-panel"><h2>Readiness</h2>@foreach($readiness['failures'] as $item)<p class="admin-feedback is-error">{{ $item }}</p>@endforeach @foreach($readiness['warnings'] as $item)<p class="admin-warning">{{ $item }}</p>@endforeach</section>

    @can(\App\Domain\Identity\Support\PermissionRegistry::MEDIA_REPLACE)
        <section class="admin-panel admin-replacement-workspace" aria-labelledby="replace-media-title" data-media-replacement>
            <div class="admin-section-heading"><p>Versioned replacement</p><h2 id="replace-media-title">Replace provider media</h2></div>
            <p>The logical media identity and all {{ $this->asset->usages->count() }} usages remain attached. The previous provider binary is retained.</p>
            <ul>@forelse($this->asset->usages as $usage)<li>{{ $usage->owner_type }} - {{ $usage->field_role }}</li>@empty<li>No current usages</li>@endforelse</ul>
            <div class="admin-upload-dropzone"><label class="admin-primary-button" for="replacement-file">Choose replacement</label><input id="replacement-file" data-replacement-file type="file" accept="{{ $this->asset->resource_type->value === 'image' ? 'image/jpeg,image/png,image/webp,image/avif' : 'video/mp4,video/webm' }}"></div>
            <div class="admin-upload-actions"><button type="button" class="admin-primary-button" data-replacement-start disabled>Upload and compare</button><button type="button" class="admin-secondary-button" data-replacement-cancel-upload>Cancel upload</button></div>
            <progress max="100" value="0" hidden></progress><p data-replacement-status aria-live="polite" tabindex="-1">No replacement selected.</p>

            @if($replacementProposal)
                <div class="admin-replacement-comparison" aria-labelledby="replacement-comparison-title">
                    <h3 id="replacement-comparison-title">Current and proposed file facts</h3>
                    <div class="admin-comparison">
                        <section><h4>Current version {{ $replacementProposal['currentFacts']['version'] }}</h4><dl><dt>Format</dt><dd>{{ $replacementProposal['currentFacts']['format'] }}</dd><dt>Dimensions</dt><dd>{{ $replacementProposal['currentFacts']['width'] }} x {{ $replacementProposal['currentFacts']['height'] }}</dd><dt>Bytes</dt><dd>{{ number_format($replacementProposal['currentFacts']['bytes']) }}</dd></dl></section>
                        <section><h4>Proposed replacement</h4><dl><dt>Format</dt><dd>{{ $replacementProposal['proposedFacts']['format'] }}</dd><dt>Dimensions</dt><dd>{{ $replacementProposal['proposedFacts']['width'] }} x {{ $replacementProposal['proposedFacts']['height'] }}</dd><dt>Bytes</dt><dd>{{ number_format($replacementProposal['proposedFacts']['bytes']) }}</dd></dl></section>
                    </div>
                    @if($replacementProposal['warnings'])<div class="admin-warning"><strong>Material-change review</strong><ul>@foreach($replacementProposal['warnings'] as $warning)<li>{{ $warning }}</li>@endforeach</ul></div>@endif
                    <div class="admin-field"><label for="replacement-reason">Replacement reason</label><textarea id="replacement-reason" wire:model="reason" maxlength="2000"></textarea></div>
                    <label class="admin-confirmation"><input type="checkbox" wire:model="replacementConfirmed"> I reviewed the proposed facts, warnings and affected usages.</label>
                    <div class="admin-upload-actions"><button type="button" class="admin-danger-button" wire:click="applyReplacement">Apply confirmed replacement</button><button type="button" class="admin-secondary-button" wire:click="cancelReplacement">Cancel replacement</button></div>
                </div>
            @endif
        </section>
    @endcan

    @can(\App\Domain\Identity\Support\PermissionRegistry::MEDIA_EDIT)<section class="admin-panel"><h2>Editorial metadata and accessibility</h2><form wire:submit="save" class="admin-media-form"><div class="admin-field"><label for="media-title">Internal title</label><input id="media-title" wire:model="internalTitle"></div><div class="admin-field"><label for="media-alt">Default alt text</label><textarea id="media-alt" wire:model="defaultAltText"></textarea></div><div class="admin-field"><label for="media-classification">Accessibility classification</label><select id="media-classification" wire:model="accessibilityClassification">@foreach(['informative','decorative','complex','text_image'] as $v)<option value="{{ $v }}">{{ str_replace('_',' ',ucfirst($v)) }}</option>@endforeach</select></div><div class="admin-field"><label for="focal-x">Focal X (0-1)</label><input id="focal-x" type="number" min="0" max="1" step=".01" wire:model="focalX"></div><div class="admin-field"><label for="focal-y">Focal Y (0-1)</label><input id="focal-y" type="number" min="0" max="1" step=".01" wire:model="focalY"></div><button class="admin-primary-button">Save metadata</button></form></section>@endcan
    <section class="admin-panel"><h2>Version history</h2><ul>@foreach($this->asset->versions as $version)<li>Version {{ $version->version_number }} - {{ $version->format }} - {{ $version->is_current ? 'Current' : 'Historical' }}</li>@endforeach</ul><h2>Usage</h2><ul>@forelse($this->asset->usages as $usage)<li>{{ $usage->owner_type }} - {{ $usage->field_role }}</li>@empty<li>Unused</li>@endforelse</ul></section>
    <section class="admin-panel"><h2>Lifecycle</h2><p>Irreversible deletion is not available. Existing references are always preserved.</p><div class="admin-field"><label for="lifecycle-reason">Reason</label><textarea id="lifecycle-reason" wire:model="reason"></textarea></div>@if($this->asset->state->value==='archived')@can(\App\Domain\Identity\Support\PermissionRegistry::MEDIA_RESTORE)<button class="admin-primary-button" wire:click="restore">Restore media</button>@endcan @else @can(\App\Domain\Identity\Support\PermissionRegistry::MEDIA_ARCHIVE)<button class="admin-danger-button" wire:click="archive">Archive media</button>@endcan @endif</section>
</div>
